# LAB 1.3 - PriorityClasses.
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
value: 1000
globalDefault: false
description: "Cargas de relleno, desalojables."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: critical-priority
value: 100000
globalDefault: false
preemptionPolicy: PreemptLowerPriority
description: "Cargas criticas: pueden desalojar Pods de menor prioridad."
