# -*- coding: utf-8 -*-
"""Contenido de la Clase 2 — Administración del Cluster: Upgrade, ETCD y RBAC."""

DECK = {
    "meta": {
        "clase_n": 2,
        "curso": "CKA Hands-On Training",
        "title": "Clase 2 — Administración del Cluster: Upgrade, ETCD y RBAC",
    },
    "slides": [
        {
            "t": "cover",
            "kicker": "CLASE 2",
            "title": "Administración del Cluster — Upgrade, ETCD y RBAC",
            "subtitle": "Mantener, recuperar y controlar el acceso a lo que sostiene tus aplicaciones",
            "stats": [
                ("180 min", "Duración"),
                ("4", "Laboratorios"),
                ("25 %", "Peso en el CKA"),
                ("1.34→1.35", "Upgrade"),
            ],
        },
        {
            "t": "list",
            "eyebrow": "Objetivos",
            "heading": "Al terminar esta clase serás capaz de…",
            "columns": 1,
            "items": [
                "Inventariar los componentes de un cluster kubeadm y sus versiones.",
                "Vaciar y devolver un nodo al servicio con cordon, drain y uncordon.",
                "Actualizar un cluster completo: control plane primero, workers después.",
                "Localizar endpoint y certificados de etcd sin buscar en Internet.",
                "Crear, validar y restaurar un snapshot de etcd.",
                "Diseñar permisos RBAC aplicando mínimo privilegio.",
                "Diagnosticar un Forbidden con kubectl auth can-i.",
            ],
        },
        {
            "t": "agenda",
            "eyebrow": "180 minutos",
            "heading": "Agenda",
            "rows": [
                ("00–12", "Repaso de la Clase 1 y objetivos"),
                ("12–35", "Conceptos: arquitectura kubeadm, static Pods, version skew"),
                ("35–50", "Demo: drain en vivo, ver a dónde se mueven los Pods, uncordon"),
                ("50–70", "LAB 2.1 — Básico: inventario, cordon, drain, uncordon"),
                ("70–105", "LAB 2.2 — Intermedio: upgrade del control plane y del worker"),
                ("105–118", "Conceptos: etcd, certificados y estrategia de backup"),
                ("118–145", "LAB 2.3 — Avanzado: snapshot, validación y restore de etcd"),
                ("145–158", "Conceptos: RBAC en 10 minutos"),
                ("158–176", "LAB 2.4 — Challenge: Forbidden en producción"),
                ("176–180", "Cierre y CKA Tips"),
            ],
        },
        {
            "t": "section", "index": 1, "eyebrow": "Bloque 1",
            "title": "Arquitectura kubeadm",
            "subtitle": "Qué hay debajo de kubectl y quién lo arranca",
        },
        {
            "t": "concept",
            "eyebrow": "Concepto",
            "heading": "El control plane no son Deployments",
            "icon": "controlplane",
            "theory": [
                "En un cluster montado con kubeadm, los componentes del control plane —kube-apiserver, kube-controller-manager, kube-scheduler y etcd— no son Deployments ni los gestiona el propio Kubernetes. Son static Pods: el kubelet del nodo maestro vigila la carpeta /etc/kubernetes/manifests/, y por cada archivo YAML que encuentra allí crea y mantiene un Pod, sin pasar por el API server ni por el scheduler.",
                "Esto tiene consecuencias prácticas muy directas. No puedes borrar estos Pods con kubectl: el kubelet los recrea al instante. Sí puedes intervenir editando su manifiesto en esa carpeta —el kubelet detecta el cambio y reinicia el componente en segundos—, y esa es la palanca principal de recuperación cuando algo va mal.",
                "El kubelet, en cambio, es un servicio de systemd normal: sobrevive aunque el API server esté caído. Por eso, cuando kubectl no responde, el diagnóstico se hace por SSH al nodo con systemctl status kubelet, journalctl -u kubelet y crictl ps -a, nunca con kubectl.",
            ],
            "points": [
                "En kubeadm, el control plane son static Pods: el kubelet los arranca leyendo archivos del disco.",
                "El scheduler no interviene y no puedes borrarlos con kubectl: el kubelet los recrea al instante.",
                "Cambiar un manifiesto de esa carpeta reinicia el componente en segundos. Es la palanca de recuperación.",
                "El kubelet, en cambio, sí es un servicio de systemd: sobrevive aunque el API server esté caído.",
            ],
            "side": {"kind": "code", "title": "/etc/kubernetes/manifests/", "lines": [
                "etcd.yaml",
                "kube-apiserver.yaml",
                "kube-controller-manager.yaml",
                "kube-scheduler.yaml",
                "",
                "# Sin kubectl:",
                "crictl ps -a",
                "journalctl -u kubelet -n 80",
            ]},
            "note": {"text": "Si kubectl no responde, la respuesta está en journalctl -u kubelet y en crictl. Nunca en kubectl."},
        },
        {
            "t": "process",
            "eyebrow": "Mantenimiento",
            "heading": "Vaciar un nodo sin cortar el servicio",
            "theory": [
                "Antes de tocar un nodo (actualizarlo, parchear el kernel, reiniciar el hardware) hay que sacarle la carga sin cortar el servicio. cordon marca el nodo como no programable: deja de aceptar Pods nuevos, pero los que ya corren siguen intactos. drain va más allá: además de acordonar, desaloja los Pods existentes para que sus controladores los recreen en otros nodos.",
                "drain se detiene a propósito en dos casos y hay que autorizarlos explícitamente. Con --ignore-daemonsets porque los Pods de un DaemonSet están atados a cada nodo y no tiene sentido moverlos. Con --delete-emptydir-data porque un emptyDir contiene datos que se perderán al recrear el Pod en otro sitio, y Kubernetes exige que confirmes que asumes esa pérdida. El mensaje de error te dice exactamente qué flag falta.",
                "uncordon revierte el acordonado y el nodo vuelve a aceptar Pods nuevos, pero los que se movieron NO regresan solos: el scheduler solo decide al crear un Pod, no reequilibra los que ya están colocados. Para repartir de nuevo hay que forzar la recreación, por ejemplo con kubectl rollout restart.",
            ],
            "steps": [
                {"title": "cordon", "body": "El nodo deja de aceptar Pods nuevos. Los actuales siguen ahí."},
                {"title": "drain", "body": "Desaloja los Pods existentes. Los controladores los recrean en otros nodos."},
                {"title": "Mantener", "body": "Upgrade, parches, reinicio del hardware."},
                {"title": "uncordon", "body": "El nodo vuelve a aceptar Pods. Los antiguos NO regresan solos."},
            ],
            "note": {"text": "drain falla dos veces a propósito: DaemonSets (--ignore-daemonsets) y datos de emptyDir (--delete-emptydir-data). Lee el mensaje: te está diciendo qué autorizar."},
        },
        {
            "t": "codeblocks",
            "eyebrow": "Aviso",
            "heading": "Kubernetes no reequilibra por sí solo",
            "accent": "danger",
            "intro": "Tras un uncordon, las réplicas no vuelven al nodo. El scheduler solo decide en el momento de CREAR un Pod; una vez colocado, nadie lo mueve. Si necesitas repartir de nuevo, fuerza la recreación.",
            "blocks": [
                {"lines": [
                    "k drain <node> --ignore-daemonsets --delete-emptydir-data",
                    "k uncordon <node>",
                    "k rollout restart deployment/<d>    # así sí se reequilibra",
                ]},
            ],
        },
        {
            "t": "lab",
            "level": "Nivel básico",
            "title": "LAB 2.1 — Inventario del cluster, cordon y drain",
            "desc": "Conocer el cluster antes de tocarlo y practicar la operación que precede a cualquier mantenimiento.",
            "steps": [
                "Tabla de versiones: nodos, cliente, servidor, kubeadm, kubelet, runtime.",
                "Identificar los cuatro static Pods y el data dir de etcd.",
                "Desplegar 4 réplicas, cordonar y comprobar que un Pod nuevo evita el nodo.",
                "Resolver por tu cuenta los dos errores que da drain.",
            ],
            "file": "CLASE-02/LABORATORIOS/LAB-01-BASICO.md",
            "duration": "20 min",
            "validation": "k get nodes -o wide",
            "accent": "blue",
        },
        {
            "t": "section", "index": 2, "eyebrow": "Bloque 2",
            "title": "Upgrade del cluster",
            "subtitle": "Una minor cada vez, y siempre en el mismo orden",
        },
        {
            "t": "chain",
            "eyebrow": "Procedimiento",
            "heading": "El orden no es negociable",
            "theory": [
                "El upgrade de un cluster kubeadm sigue un orden fijo que no es arbitrario. Primero el control plane, después los workers, y siempre una minor cada vez (1.33 → 1.34 → 1.35, nunca saltos). El motivo es la regla de version skew: el kubelet puede estar en la misma versión que el API server o hasta tres minors por debajo, pero nunca por encima. Si actualizaras el kubelet primero, el cluster quedaría en un estado no soportado.",
                "Dentro de cada nodo, kubeadm va primero porque es quien reescribe los manifiestos de los static Pods con las imágenes nuevas: kubeadm upgrade apply <versión> en el primer control plane, kubeadm upgrade node en el resto de nodos (no aplican una versión de cluster, solo se ponen al día). Solo después se actualizan los paquetes kubelet y kubectl, se hace systemctl daemon-reload y se reinicia el kubelet.",
                "El snapshot de etcd va antes de empezar, sin excepción: es la única red de seguridad si el upgrade deja el cluster inconsistente. Y en cada nodo hay que acordonar y drenar antes de reiniciar el kubelet, y hacer uncordon al terminar.",
            ],
            "nodes": ["Validar versiones", "Snapshot de etcd", "kubeadm", "upgrade plan / apply",
                      "drain", "kubelet + kubectl", "restart kubelet", "uncordon"],
            "detail": {"label": "Por qué ese orden", "lines": [
                "kubeadm escribe los manifiestos nuevos de los static Pods: tiene que ir primero.",
                "kubelet solo puede estar igual o por debajo del API server, nunca por encima. Por eso va después.",
                "En los workers se usa kubeadm upgrade node, no apply: no aplican una versión de cluster.",
                "Nunca se saltan minors: 1.34 → 1.35 → 1.36.",
                "Y siempre: systemctl daemon-reload antes de restart.",
            ]},
        },
        {
            "t": "codeblocks",
            "eyebrow": "Actualización técnica",
            "heading": "El repositorio cambió: hay uno por cada minor",
            "accent": "warn",
            "intro": "El error número uno del upgrade. apt install kubeadm=1.35.x falla con «Version not found» no porque la versión no exista, sino porque el repositorio sigue apuntando a la minor anterior. Los antiguos apt.kubernetes.io y packages.cloud.google.com están retirados.",
            "blocks": [
                {"lines": [
                    "sed -i 's#/v1.34/#/v1.35/#' /etc/apt/sources.list.d/kubernetes.list",
                    "curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.35/deb/Release.key \\",
                    "  | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg --yes",
                    "apt update && apt-cache madison kubeadm | head",
                ]},
            ],
        },
        {
            "t": "codeblocks",
            "eyebrow": "Secuencia",
            "heading": "Control plane y worker, lado a lado",
            "blocks": [
                {"label": "Control plane", "lines": [
                    "apt-mark unhold kubeadm && apt install -y kubeadm=1.35.0-1.1 && apt-mark hold kubeadm",
                    "kubeadm upgrade plan",
                    "kubeadm upgrade apply v1.35.0",
                    "kubectl drain cka-master --ignore-daemonsets --delete-emptydir-data",
                    "apt-mark unhold kubelet kubectl && apt install -y kubelet=1.35.0-1.1 kubectl=1.35.0-1.1",
                    "systemctl daemon-reload && systemctl restart kubelet",
                    "kubectl uncordon cka-master",
                ]},
                {"label": "Worker: idéntico, cambiando una sola línea", "lines": [
                    "kubeadm upgrade node        # en lugar de 'kubeadm upgrade apply'",
                ]},
            ],
            "note": {"text": "En el examen léelo dos veces: casi siempre piden actualizar solo el control plane, o solo un nodo concreto."},
        },
        {
            "t": "lab",
            "level": "Nivel intermedio",
            "title": "LAB 2.2 — Upgrade kubeadm v1.34 → v1.35",
            "desc": "Actualizar el cluster completo sin que la aplicación testigo deje de responder en ningún momento.",
            "steps": [
                "Snapshot de etcd ANTES de empezar. Sin excepción.",
                "Repositorio a la minor de destino en cada nodo.",
                "kubeadm → upgrade plan → upgrade apply → kubelet/kubectl → restart → uncordon.",
                "Workers uno a uno, con kubeadm upgrade node.",
                "Vigilar la disponibilidad en otra terminal durante toda la ventana.",
            ],
            "file": "CLASE-02/LABORATORIOS/LAB-02-INTERMEDIO.md",
            "duration": "35 min",
            "validation": "k get nodes -o wide",
            "accent": "blue",
        },
        {
            "t": "section", "index": 3, "eyebrow": "Bloque 3",
            "title": "ETCD",
            "subtitle": "Todo el estado del cluster cabe en un archivo",
        },
        {
            "t": "concept",
            "eyebrow": "Concepto",
            "heading": "El backup que nadie ha restaurado no es un backup",
            "theory": [
                "etcd es la única fuente de verdad del cluster: guarda todos los objetos (Pods, Deployments, Secrets, ConfigMaps, RBAC, estado de los nodos) como pares clave-valor. Si etcd se corrompe o se pierde, el cluster deja de existir aunque los nodos sigan encendidos. Restaurar un snapshot devuelve el cluster exactamente al instante en que se tomó; todo lo creado después desaparece, y esa ventana de pérdida (el RPO) es el argumento para automatizar los backups.",
                "No hace falta memorizar rutas ni puertos: el manifiesto del API server (/etc/kubernetes/manifests/kube-apiserver.yaml) declara en sus argumentos el endpoint de etcd y los tres certificados que usa para hablar con él (--etcd-cafile, --etcd-certfile, --etcd-keyfile, --etcd-servers). Un grep sobre ese archivo te da todo lo necesario.",
                "El restore va SIEMPRE a un data-dir nuevo y con el control plane parado. El procedimiento: mover los manifiestos fuera de la carpeta para detener API server y etcd, ejecutar el restore hacia el directorio nuevo, reapuntar el hostPath del volumen de datos de etcd en su manifiesto, y devolver los manifiestos para que el kubelet lo levante todo.",
            ],
            "points": [
                "etcd guarda el estado completo del cluster. Restaurarlo devuelve el cluster a ese instante exacto.",
                "Todo lo creado después del snapshot desaparece. Eso es el RPO, y es el argumento para automatizar.",
                "No hace falta memorizar rutas: el manifiesto del API server declara el endpoint y los certificados que usa.",
                "El restore va SIEMPRE a un data dir nuevo, con el control plane parado.",
            ],
            "side": {"kind": "code", "title": "De dónde salen las rutas", "lines": [
                "grep etcd \\",
                "  /etc/kubernetes/manifests/ \\",
                "  kube-apiserver.yaml",
                "",
                "--etcd-cafile=.../etcd/ca.crt",
                "--etcd-certfile=...client.crt",
                "--etcd-keyfile=...client.key",
                "--etcd-servers=https://127.0.0.1:2379",
            ]},
        },
        {
            "t": "columns",
            "eyebrow": "Actualización técnica",
            "heading": "etcdctl y etcdutl no son lo mismo",
            "theory": [
                "Son dos binarios distintos con propósitos distintos y confundirlos hace perder tiempo en el examen. etcdctl es el cliente de red: habla con una instancia de etcd EN FUNCIONAMIENTO, así que necesita el endpoint y los certificados. Con él se comprueba la salud (endpoint health, endpoint status) y se toma el snapshot en caliente (snapshot save).",
                "etcdutl es la herramienta offline: trabaja directamente sobre el ARCHIVO .db del snapshot, sin cluster, sin endpoint y sin certificados. Con él se valida la integridad del snapshot (snapshot status) y se hace el restore (snapshot restore). Si un procedimiento te pide certificados para consultar el estado de un archivo, estás usando el binario equivocado.",
                "Dos notas de versión: snapshot restore en etcdctl está deprecado y avisa por consola —el comando correcto hoy es etcdutl snapshot restore—; y la variable ETCDCTL_API=3 ya no hace falta, porque la v3 es el valor por defecto desde hace varias versiones.",
            ],
            "cols": [
                {"title": "etcdctl", "subtitle": "Habla con un etcd VIVO", "lines": [
                    "Necesita certificados y endpoint.",
                    "endpoint health · endpoint status",
                    "snapshot save",
                    "snapshot restore está DEPRECADO: avisa por consola.",
                ]},
                {"title": "etcdutl", "subtitle": "Trabaja sobre un ARCHIVO", "accent": "warn", "lines": [
                    "No necesita certificados ni endpoint.",
                    "snapshot status — valida el .db",
                    "snapshot restore — es el comando correcto hoy",
                    "Si te piden certificados para un status, estás usando el binario equivocado.",
                ]},
            ],
            "note": {"text": "ETCDCTL_API=3 ya no hace falta: v3 es el valor por defecto desde hace varias versiones."},
        },
        {
            "t": "codeblocks",
            "eyebrow": "Los tres comandos",
            "heading": "Backup, validación y restore",
            "blocks": [
                {"label": "1 · Snapshot (memoriza esta línea)", "lines": [
                    "etcdctl --endpoints=https://127.0.0.1:2379 \\",
                    "  --cacert=/etc/kubernetes/pki/etcd/ca.crt \\",
                    "  --cert=/etc/kubernetes/pki/etcd/server.crt \\",
                    "  --key=/etc/kubernetes/pki/etcd/server.key \\",
                    "  snapshot save /opt/backup/etcd.db",
                ]},
                {"label": "2 · Validar   ·   3 · Restaurar", "lines": [
                    "etcdutl snapshot status  /opt/backup/etcd.db --write-out=table",
                    "etcdutl snapshot restore /opt/backup/etcd.db --data-dir /var/lib/etcd-restore",
                ]},
            ],
            "note": {"text": "Y después: parar el control plane moviendo los manifiestos, reapuntar el hostPath del volumen etcd-data, y devolverlos."},
        },
        {
            "t": "lab",
            "level": "Nivel avanzado",
            "title": "LAB 2.3 — ETCD: snapshot, validación y restore",
            "desc": "Demostrar que el backup funciona. Un snapshot que nadie ha restaurado nunca no es un backup.",
            "steps": [
                "Deducir endpoint, certificados y data dir leyendo los manifiestos.",
                "Crear el Deployment 'antes', tomar snapshot, validarlo y anotar el número de claves.",
                "Crear el Deployment 'despues' — que se perderá.",
                "Restaurar a un data dir nuevo, parar el control plane y reapuntar etcd.yaml.",
                "Explicar por escrito por qué 'despues' desapareció.",
            ],
            "file": "CLASE-02/LABORATORIOS/LAB-03-AVANZADO.md",
            "duration": "27 min",
            "validation": "etcdutl snapshot status",
            "accent": "blue",
        },
        {
            "t": "section", "index": 4, "eyebrow": "Bloque 4",
            "title": "RBAC",
            "subtitle": "Quién puede hacer qué, y dónde",
        },
        {
            "t": "concept",
            "eyebrow": "Concepto",
            "heading": "RBAC en cuatro ideas",
            "theory": [
                "RBAC (Role-Based Access Control) responde a una sola pregunta: ¿esta identidad puede ejecutar este verbo sobre este recurso, en este ámbito? Es whitelisting puro: todo lo que no se concede explícitamente está denegado, y no existen reglas de denegación. Los permisos son aditivos: si una identidad tiene varios bindings, sus permisos efectivos son la unión de todos, y el orden en que se evalúan no importa.",
                "Hay dos tipos de sujeto. Las ServiceAccounts sí son objetos del API, viven en un namespace y su identidad real es system:serviceaccount:<ns>:<nombre>. Los usuarios y grupos NO son objetos: no se crean con kubectl; existen únicamente dentro de los bindings y en los certificados o tokens que presenta el cliente al autenticarse.",
                "Cuatro objetos combinan el qué y el a-quién. Role y ClusterRole definen QUÉ se puede hacer (verbos sobre recursos); el Role está limitado a un namespace, el ClusterRole no tiene ámbito. RoleBinding y ClusterRoleBinding asignan un rol A UN SUJETO; el RoleBinding concede solo en su namespace, el ClusterRoleBinding en todo el cluster.",
            ],
            "points": [
                "Es whitelisting puro: todo lo que no se concede explícitamente está denegado.",
                "Los permisos son aditivos. No existen reglas de denegación: solo se suman.",
                "Los usuarios NO son objetos del API. jane y jim solo existen dentro de los bindings y en los certificados.",
                "Las ServiceAccounts sí son objetos, y su identidad real es system:serviceaccount:<ns>:<nombre>.",
            ],
            "side": {"kind": "text", "title": "Los cuatro objetos", "lines": [
                "Role — qué se puede hacer, en un namespace",
                "ClusterRole — qué se puede hacer, sin ámbito",
                "RoleBinding — a quién, en un namespace",
                "ClusterRoleBinding — a quién, en todo el cluster",
            ]},
        },
        {
            "t": "table",
            "eyebrow": "La pregunta que lo resuelve todo",
            "heading": "¿El permiso vale en un namespace o en todos?",
            "theory": [
                "El alcance real de un permiso lo determina el BINDING, no el rol. Un Role con un RoleBinding concede solo en ese namespace, como cabe esperar. Un ClusterRole con un ClusterRoleBinding concede en todo el cluster, incluidos los recursos que no tienen namespace (nodos, PersistentVolumes, la propia definición de namespaces).",
                "La combinación potente y a la vez peligrosa es un ClusterRole con un RoleBinding: reutiliza una definición de permisos común (por ejemplo, «leer pods») pero la aplica solo dentro del namespace del binding. Es la forma correcta de dar permisos acotados sin repetir el mismo Role en cada namespace.",
                "La combinación inválida es un Role con un ClusterRoleBinding: el API la acepta sin error, pero no concede absolutamente nada. Y el error más caro en producción es poner un ClusterRoleBinding donde debía ir un RoleBinding: se cree que se ha dado acceso a un namespace y en realidad se ha dado a los treinta. Auditar siempre con kubectl auth can-i --as, nunca leyendo los YAML.",
            ],
            "headers": ["Role usado", "Binding usado", "Alcance resultante"],
            "weights": [2, 2, 5],
            "mono_last": False,
            "rows": [
                ["Role", "RoleBinding", "Solo ese namespace"],
                ["ClusterRole", "ClusterRoleBinding", "Todo el cluster, incluidos recursos no namespaced"],
                ["ClusterRole", "RoleBinding", "Solo ese namespace, reutilizando la definición"],
                ["Role", "ClusterRoleBinding", "NO ES VÁLIDO — el API lo acepta y no concede nada"],
            ],
            "note": {"text": "Poner un ClusterRoleBinding donde debía ir un RoleBinding es el fallo de RBAC más común y más caro en producción."},
        },
        {
            "t": "codeblocks",
            "eyebrow": "Imperativo",
            "heading": "RBAC sin pelearse con la indentación",
            "blocks": [
                {"label": "Crear", "lines": [
                    "k create role r1 --verb=get,list --resource=pods -n ns1",
                    "k create rolebinding rb1 --role=r1 --user=jane -n ns1",
                    "k create clusterrole cr1 --verb=delete --resource=deployments",
                    "k create clusterrolebinding crb1 --clusterrole=cr1 --user=jane",
                    "k create rolebinding rb2 --clusterrole=cr1 --user=jim -n red   # alcance limitado",
                    "k create rolebinding rb3 --role=r1 --serviceaccount=ns1:processor -n ns1",
                ]},
                {"label": "Auditar", "lines": [
                    "k auth can-i delete secrets --as jane -n red",
                    "k auth can-i --list --as jane -n red",
                    "k auth can-i create pods --as system:serviceaccount:ns1:processor -n ns1",
                ]},
            ],
            "note": {"text": "auth can-i responde yes o no. Es la única forma fiable de auditar: leer los YAML induce a error."},
        },
        {
            "t": "lab",
            "level": "Challenge — el escenario arranca roto",
            "title": "LAB 2.4 — Challenge: Forbidden en producción",
            "desc": "La implementación RBAC no coincide con el diseño aprobado. Faltan permisos y, peor, sobran otros.",
            "steps": [
                "Prepara el escenario: RECURSOS/SCRIPTS/setup-lab.sh",
                "Audita con auth can-i y construye la tabla diseño vs. estado real.",
                "Identifica el permiso EXCESIVO y explica por qué es peligroso.",
                "Corrige con mínimo privilegio. Prohibido cluster-admin, admin y edit.",
            ],
            "file": "CLASE-02/LABORATORIOS/LAB-04-CHALLENGE.md",
            "duration": "18 min",
            "validation": "./validate-lab.sh",
            "accent": "danger",
        },
        {
            "t": "list",
            "eyebrow": "Checklist",
            "heading": "Comprueba que puedes hacer esto sin apuntes",
            "columns": 2,
            "style": "check",
            "items": [
                "Listo versiones de kubeadm, kubelet, kubectl y del servidor.",
                "Vacío un nodo y sé por qué drain necesita --ignore-daemonsets.",
                "Actualizo el control plane con kubeadm upgrade apply.",
                "Actualizo un worker con kubeadm upgrade node.",
                "Sé el orden: kubeadm, luego kubelet y kubectl.",
                "Localizo endpoint y certificados de etcd sin buscar en Google.",
                "Creo un snapshot y lo valido con etcdutl snapshot status.",
                "Restauro etcd y recupero el cluster.",
                "Distingo Role de ClusterRole y RoleBinding de ClusterRoleBinding.",
                "Diagnostico un Forbidden con auth can-i --as.",
            ],
        },
        {
            "t": "closing",
            "eyebrow": "Cierre de la clase",
            "title": "Clase 2 completada",
            "paragraphs": [
                "Sabes mantener el cluster, recuperarlo de un desastre y controlar quién hace qué dentro de él.",
                "En la Clase 3 volvemos a las aplicaciones, pero a las difíciles: las que tienen estado. Workloads, almacenamiento persistente y StatefulSets.",
                "Repasa antes: la relación Deployment → ReplicaSet → Pod.",
            ],
        },
    ],
}
