# -*- coding: utf-8 -*-
"""Contenido de la Clase 5 — Services, Ingress, CoreDNS y NetworkPolicy."""

DECK = {
    "meta": {
        "clase_n": 5,
        "curso": "CKA Hands-On Training",
        "title": "Clase 5 — Services, Ingress, CoreDNS y NetworkPolicy",
    },
    "slides": [
        {
            "t": "cover",
            "kicker": "CLASE 5",
            "title": "Services, Ingress, CoreDNS y NetworkPolicy",
            "subtitle": "Publicar aplicaciones y decidir exactamente quién puede hablar con quién",
            "stats": [
                ("180 min", "Duración"),
                ("4", "Laboratorios"),
                ("20 %", "Peso en el CKA"),
                ("TLS", "HTTPS propio"),
            ],
        },
        {
            "t": "list",
            "eyebrow": "Objetivos",
            "heading": "Al terminar esta clase serás capaz de…",
            "columns": 1,
            "items": [
                "Elegir el tipo de Service correcto para cada necesidad de publicación.",
                "Explicar el modelo de red: Pod-to-Pod, Pod-to-Service y entrada desde fuera.",
                "Resolver nombres con CoreDNS y diagnosticar un fallo de resolución.",
                "Publicar varias aplicaciones tras una sola entrada, con HTTP y HTTPS.",
                "Situar Gateway API frente a Ingress y saber por qué existe.",
                "Escribir NetworkPolicies de Ingress y Egress, incluyendo default deny.",
                "Distinguir un fallo de DNS de uno de endpoints, de política o de Ingress.",
            ],
        },
        {
            "t": "agenda",
            "eyebrow": "180 minutos",
            "heading": "Agenda",
            "rows": [
                ("00–10", "Repaso de la Clase 4 y objetivos"),
                ("10–30", "Conceptos: modelo de red, tipos de Service, EndpointSlice"),
                ("30–45", "Conceptos: CoreDNS y resolución de nombres"),
                ("45–68", "LAB 5.1 — Básico: Services y DNS"),
                ("68–85", "Conceptos: Ingress, controlador, TLS y Gateway API"),
                ("85–120", "LAB 5.2 — Intermedio: Ingress con HTTP y HTTPS"),
                ("120–133", "Conceptos: NetworkPolicy"),
                ("133–160", "LAB 5.3 — Avanzado: aislar frontend y backend"),
                ("160–176", "LAB 5.4 — Challenge: «la red está rota»"),
                ("176–180", "Cierre y CKA Tips"),
            ],
        },
        {
            "t": "section", "index": 1, "eyebrow": "Bloque 1",
            "title": "Services y DNS",
            "subtitle": "Lo que hay debajo de cualquier problema de red",
        },
        {
            "t": "chain",
            "eyebrow": "Ruta del tráfico",
            "heading": "Cómo llega un paquete a un Pod",
            "nodes": ["Cliente", "ClusterIP (virtual)", "kube-proxy · iptables/IPVS",
                      "EndpointSlice", "IP del Pod : targetPort"],
            "detail": {"label": "Tres consecuencias prácticas", "lines": [
                "La ClusterIP no existe en ninguna interfaz de red: es una regla, no una dirección real.",
                "El DNS NO balancea. Resuelve siempre a la misma ClusterIP; quien reparte es kube-proxy.",
                "Un Pod que no está Ready desaparece del EndpointSlice y deja de recibir tráfico. Es lo que hace que un rollout roto no rompa el servicio.",
                "Por eso: nslookup OK + curl timeout = problema de endpoints, NO de DNS.",
            ]},
        },
        {
            "t": "cards",
            "eyebrow": "Tipos",
            "heading": "Cuatro tipos y un caso especial",
            "cols": 3,
            "cards": [
                {"title": "ClusterIP", "body": "Por defecto. Solo dentro del cluster. Para que un componente hable con otro."},
                {"title": "NodePort", "body": "Mismo puerto en todos los nodos, rango 30000–32767. Laboratorio y balanceadores propios."},
                {"title": "LoadBalancer", "body": "IP pública del proveedor de nube. Una por Service: caro cuando hay muchos."},
                {"title": "ExternalName", "body": "Ni IP ni endpoints. CoreDNS devuelve un CNAME a un nombre externo. No hay proxy."},
                {"title": "Headless", "body": "clusterIP: None. El DNS devuelve las IP de los Pods, no una VIP. Base del StatefulSet."},
                {"title": "El error de siempre", "body": "port es el puerto del Service; targetPort el del contenedor; nodePort el del nodo."},
            ],
        },
        {
            "t": "concept",
            "eyebrow": "CoreDNS",
            "heading": "Cómo encuentra un Pod a otro por nombre",
            "points": [
                "CoreDNS vive en kube-system. Su Service se sigue llamando kube-dns por motivos históricos.",
                "El FQDN de un Service es <svc>.<ns>.svc.cluster.local; el de un Pod de StatefulSet añade el nombre del Pod delante.",
                "search hace que dentro del namespace baste con escribir el nombre corto del Service.",
                "ndots:5 significa que un nombre con menos de 5 puntos prueba primero los sufijos de search.",
            ],
            "side": {"kind": "code", "title": "/etc/resolv.conf de un Pod", "lines": [
                "nameserver 10.96.0.10",
                "search c5-basico.svc.cluster.local",
                "       svc.cluster.local",
                "       cluster.local",
                "options ndots:5",
                "",
                "# Diagnóstico rápido:",
                "k run tmp --rm -it \\",
                "  --image=busybox:1.36 \\",
                "  --restart=Never -- \\",
                "  nslookup <svc>.<ns>",
            ]},
        },
        {
            "t": "lab",
            "level": "Nivel básico",
            "title": "LAB 5.1 — Services, EndpointSlice y CoreDNS",
            "desc": "Publicar la misma aplicación con distintos tipos de Service y entender exactamente cómo un Pod encuentra a otro.",
            "steps": [
                "ClusterIP, NodePort con nodePort 31500 y ExternalName. Averiguar qué hace el último.",
                "Comprobar que dos Services distintos comparten los mismos endpoints.",
                "Provocar que una réplica deje de estar Ready y ver desaparecer su dirección.",
                "Leer /etc/resolv.conf, explicar search y ndots, y comprobar quién balancea.",
                "Activar y revertir el log de consultas de CoreDNS.",
            ],
            "file": "CLASE-05/LABORATORIOS/LAB-01-BASICO.md",
            "duration": "23 min",
            "validation": "k get endpointslices",
            "accent": "blue",
        },
        {
            "t": "section", "index": 2, "eyebrow": "Bloque 2",
            "title": "Ingress y Gateway API",
            "subtitle": "Una sola puerta de entrada para muchas aplicaciones",
        },
        {
            "t": "chain",
            "eyebrow": "Arquitectura",
            "heading": "Del cliente al contenedor",
            "nodes": ["CLIENTE", "INGRESS CONTROLLER (proxy L7)", "SERVICE", "ENDPOINTSLICE", "POD"],
            "detail": {"label": "Lo que hay que entender", "lines": [
                "El objeto Ingress es solo una declaración. Sin un controlador que la lea, no hace absolutamente nada.",
                "El controlador termina el TLS en el borde: del controlador al Pod el tráfico va en claro.",
                "El Secret TLS debe estar en el MISMO namespace que el Ingress.",
                "Si ingressClassName no coincide con ninguna IngressClass registrada, nadie adopta el Ingress: ADDRESS queda vacío y no hay ningún error.",
                "Verifica los Services ANTES de crear el Ingress. Si no tienen endpoints, verás 503 y buscarás en el sitio equivocado.",
            ]},
        },
        {
            "t": "codeblocks",
            "eyebrow": "Actualización técnica · marzo 2026",
            "heading": "ingress-nginx de la comunidad fue retirado",
            "accent": "warn",
            "intro": "El proyecto kubernetes/ingress-nginx está archivado desde marzo de 2026: no hay más releases, ni correcciones, ni parches de seguridad. Lo usaba alrededor de la mitad de los clusters del ecosistema, y el sucesor previsto (InGate) nunca maduró y también se retiró.",
            "blocks": [
                {"lines": [
                    "# La API Ingress NO está deprecada: sigue vigente y sigue en el examen.",
                    "# Lo retirado es UNA implementación concreta.",
                    "#",
                    "# En este curso usamos un controlador mantenido (Traefik).",
                    "# Los manifiestos Ingress que escribes son los mismos:",
                    "# solo cambia el ingressClassName.",
                ]},
            ],
            "note": {"text": "Consecuencia práctica: las anotaciones NO son portables entre controladores. Fue una de las causas del problema."},
        },
        {
            "t": "columns",
            "eyebrow": "Presente y futuro",
            "heading": "Ingress frente a Gateway API",
            "cols": [
                {"title": "Ingress", "subtitle": "Lo que se pide hoy en el examen", "lines": [
                    "Un solo objeto para todo: reglas, TLS y configuración.",
                    "Todo lo que no encaja se resuelve con anotaciones propietarias.",
                    "Esa flexibilidad se volvió una carga de mantenimiento y un riesgo de seguridad.",
                    "Sigue siendo estándar y ampliamente desplegado.",
                ]},
                {"title": "Gateway API", "subtitle": "Hacia donde va el ecosistema", "accent": "ok", "lines": [
                    "GatewayClass, Gateway y HTTPRoute: tres objetos, tres responsables.",
                    "Filtros tipados en lugar de anotaciones: URLRewrite, RequestHeaderModifier.",
                    "Rutas entre namespaces controladas con ReferenceGrant.",
                    "Ya figura en el currículum CKA vigente.",
                ]},
            ],
            "note": {"text": "Manifiesto de referencia con el mismo routing expresado en Gateway API: CLASE-05/RECURSOS/YAML/04-gateway-api.yaml"},
        },
        {
            "t": "codeblocks",
            "eyebrow": "Sintaxis",
            "heading": "Ingress con routing por path y TLS",
            "blocks": [
                {"label": "El manifiesto", "lines": [
                    "apiVersion: networking.k8s.io/v1",
                    "kind: Ingress",
                    "metadata: {name: app-ingress, namespace: c5-ingress}",
                    "spec:",
                    "  ingressClassName: traefik        # <- k get ingressclass",
                    "  tls:",
                    '    - hosts: ["secure-ingress.com"]',
                    "      secretName: secure-ingress   # <- Secret kubernetes.io/tls, MISMO namespace",
                    "  rules:",
                    "    - host: secure-ingress.com",
                    "      http:",
                    "        paths:",
                    "          - {path: /service1, pathType: Prefix,",
                    "             backend: {service: {name: service1, port: {number: 80}}}}",
                ]},
                {"label": "Probar sin tocar /etc/hosts", "lines": [
                    "curl -kv https://secure-ingress.com:32443/service2 \\",
                    "  --resolve secure-ingress.com:32443:<IP-NODO>",
                ]},
            ],
        },
        {
            "t": "lab",
            "level": "Nivel intermedio",
            "title": "LAB 5.2 — Ingress con HTTP, HTTPS y routing por path",
            "desc": "Publicar dos aplicaciones tras una sola entrada, primero en HTTP y después con un certificado propio.",
            "steps": [
                "Instalar un controlador mantenido y anotar su IngressClass y sus nodePort.",
                "VERIFICAR los Services antes de tocar el Ingress. Si esto falla, el Ingress también.",
                "Dos reglas de path con pathType: Prefix. Investigar la reescritura de path.",
                "Certificado con CN=secure-ingress.com y Secret kubernetes.io/tls.",
                "Anotar subject, issuer, versión TLS y código HTTP de la salida verbose.",
            ],
            "file": "CLASE-05/LABORATORIOS/LAB-02-INTERMEDIO.md",
            "duration": "35 min",
            "validation": "k get ingressclass",
            "accent": "blue",
        },
        {
            "t": "section", "index": 3, "eyebrow": "Bloque 3",
            "title": "NetworkPolicy",
            "subtitle": "Reglas de firewall a nivel de Pod",
        },
        {
            "t": "concept",
            "eyebrow": "Concepto",
            "heading": "Cuatro reglas que lo explican todo",
            "points": [
                "Un Pod al que no selecciona ninguna política acepta todo el tráfico. El aislamiento no es el estado por defecto.",
                "En cuanto UNA política lo selecciona para un policyType, queda aislado para ese tipo y solo pasa lo autorizado.",
                "Las políticas son ADITIVAS: se aplica la unión de todas. No existen reglas de denegación y el orden no importa.",
                "Ingress y Egress son independientes: para que A hable con B hacen falta DOS permisos, salida en A y entrada en B.",
            ],
            "side": {"kind": "code", "title": "Default deny", "lines": [
                "spec:",
                "  podSelector: {}   # todos",
                "  policyTypes:",
                "    - Ingress",
                "    - Egress",
                "",
                "# Sin secciones ingress/egress",
                "# = denegar todo",
                "",
                "# Requisito previo:",
                "# que tu CNI implemente",
                "# NetworkPolicy",
            ]},
        },
        {
            "t": "codeblocks",
            "eyebrow": "El fallo estrella",
            "heading": "Un default deny rompe el DNS",
            "accent": "danger",
            "intro": "En cuanto aplicas una política de egress, el tráfico al puerto 53 hacia CoreDNS también queda bloqueado. Nada resuelve, y el síntoma se confunde con «la red está muerta» o «CoreDNS se ha caído». Hay que permitirlo explícitamente.",
            "blocks": [
                {"lines": [
                    "egress:",
                    "  - to:",
                    "      - namespaceSelector:",
                    "          matchLabels: {kubernetes.io/metadata.name: kube-system}",
                    "    ports:",
                    "      - {protocol: UDP, port: 53}",
                    "      - {protocol: TCP, port: 53}",
                ]},
            ],
            "note": {"text": "Kubernetes añade automáticamente el label kubernetes.io/metadata.name a todos los namespaces. Úsalo."},
        },
        {
            "t": "columns",
            "eyebrow": "Un guion lo cambia todo",
            "heading": "AND frente a OR en los selectores",
            "cols": [
                {"title": "AND — un solo elemento", "subtitle": "Ese Pod, en ese namespace", "lines": [
                    "- from:",
                    "    - namespaceSelector: {...}",
                    "      podSelector: {...}",
                    "Las dos condiciones deben cumplirse a la vez.",
                ]},
                {"title": "OR — dos elementos", "subtitle": "Ese namespace, O ese Pod", "accent": "danger", "lines": [
                    "- from:",
                    "    - namespaceSelector: {...}",
                    "    - podSelector: {...}",
                    "Basta con que se cumpla una. Concede mucho más de lo que crees.",
                ]},
            ],
            "note": {"text": "Es la diferencia entre una política correcta y un agujero de seguridad, y es un solo guion."},
        },
        {
            "t": "lab",
            "level": "Nivel avanzado — solo requerimientos",
            "title": "LAB 5.3 — NetworkPolicy: aislar frontend y backend",
            "desc": "Pasar de un cluster totalmente abierto a un modelo donde solo circula el tráfico autorizado, sin dejarlo inutilizable.",
            "steps": [
                "Verificar PRIMERO que tu CNI implementa NetworkPolicy.",
                "Documentar la conectividad de partida antes de aplicar nada.",
                "Aplicar default deny, comprobar qué se rompió y explicar el efecto sobre el DNS.",
                "Permitir DNS, frontend→backend, y backend→namespace de datos.",
                "Añadir una política más sin borrar ninguna y explicar el carácter aditivo.",
            ],
            "file": "CLASE-05/LABORATORIOS/LAB-03-AVANZADO.md",
            "duration": "27 min",
            "validation": "k get networkpolicy",
            "accent": "blue",
        },
        {
            "t": "lab",
            "level": "Challenge — el escenario arranca roto",
            "title": "LAB 5.4 — Challenge: «la red está rota»",
            "desc": "Cuatro fallos en cuatro capas distintas, todos con el mismo síntoma aparente: «no llego».",
            "steps": [
                "Prepara el escenario: RECURSOS/SCRIPTS/setup-lab.sh",
                "Empieza el diagnóstico DENTRO del cluster, nunca por el curl externo.",
                "Ruta: Pod → Service → EndpointSlice → DNS → NetworkPolicy → Ingress → Cliente.",
                "Prohibido borrar default-deny y prohibido convertir Services a NodePort.",
            ],
            "file": "CLASE-05/LABORATORIOS/LAB-04-CHALLENGE.md",
            "duration": "18 min",
            "validation": "./validate-lab.sh",
            "accent": "danger",
        },
        {
            "t": "table",
            "eyebrow": "Mental model",
            "heading": "Traducción de síntomas de red",
            "headers": ["Lo que observas", "Dónde está el problema", "Comando"],
            "weights": [3, 4, 3],
            "rows": [
                ["nslookup falla", "DNS, o política de egress al 53", "describe networkpolicy"],
                ["nslookup OK, curl timeout", "Endpoints o NetworkPolicy", "get endpointslices"],
                ["EndpointSlice vacío", "Selector del Service o labels del Pod", "get pods --show-labels"],
                ["Hay endpoints, curl falla", "targetPort o política de ingress", "get svc -o yaml"],
                ["Interno OK, externo falla", "Ingress, clase o controlador", "get ingress,ingressclass"],
            ],
        },
        {
            "t": "list",
            "eyebrow": "Checklist",
            "heading": "Comprueba que puedes hacer esto sin apuntes",
            "columns": 2,
            "style": "check",
            "items": [
                "Elijo el tipo de Service adecuado y sé qué hace cada uno.",
                "Explico la cadena Service → EndpointSlice → Pod.",
                "Resuelvo un Service por FQDN y leo /etc/resolv.conf de un Pod.",
                "Distingo un fallo de DNS de uno de endpoints.",
                "Publico dos aplicaciones por path con un solo Ingress.",
                "Creo un TLS Secret y lo asocio a un Ingress por host.",
                "Explico qué es Gateway API y por qué existe.",
                "Escribo una NetworkPolicy default deny.",
                "Permito DNS explícitamente en una política de egress.",
                "Distingo el AND del OR en namespaceSelector y podSelector.",
            ],
        },
        {
            "t": "closing",
            "eyebrow": "Cierre de la clase",
            "title": "Clase 5 completada",
            "paragraphs": [
                "Ya sabes publicar aplicaciones y controlar el tráfico entre ellas.",
                "La Clase 6 no introduce temas nuevos: usa todo lo anterior contra escenarios rotos. Es el 30 % del examen y la razón por la que has hecho las cinco clases previas.",
                "Llega con los seis mental models frescos. Los vas a necesitar todos.",
            ],
        },
    ],
}
