# -*- coding: utf-8 -*-
"""Contenido de la Clase 3 — Workloads, Storage y StatefulSets."""

DECK = {
    "meta": {
        "clase_n": 3,
        "curso": "CKA Hands-On Training",
        "title": "Clase 3 — Workloads, Storage y StatefulSets",
    },
    "slides": [
        {
            "t": "cover",
            "kicker": "CLASE 3",
            "title": "Workloads, Storage y StatefulSets",
            "subtitle": "Aplicaciones que no pueden permitirse perder sus datos",
            "stats": [
                ("180 min", "Duración"),
                ("4", "Laboratorios"),
                ("10 %", "Storage en el CKA"),
                ("RWO", "Modo clave"),
            ],
        },
        {
            "t": "list",
            "eyebrow": "Objetivos",
            "heading": "Al terminar esta clase serás capaz de…",
            "columns": 1,
            "items": [
                "Explicar la cadena Deployment → ReplicaSet → Pod y demostrar el self-healing.",
                "Elegir el controlador correcto para cada tipo de carga.",
                "Compartir datos entre contenedores de un Pod con emptyDir.",
                "Aprovisionar almacenamiento estático y dinámico.",
                "Enlazar PV, PVC y Pod, y explicar por qué un PVC queda Pending.",
                "Desplegar un StatefulSet con Headless Service y volumeClaimTemplates.",
                "Diagnosticar fallos de almacenamiento con un método reproducible.",
            ],
        },
        {
            "t": "agenda",
            "eyebrow": "180 minutos",
            "heading": "Agenda",
            "rows": [
                ("00–12", "Repaso de la Clase 2 y objetivos"),
                ("12–35", "Conceptos: controladores de workload y self-healing"),
                ("35–50", "Demo: borrar un Pod de un Deployment y de un StatefulSet"),
                ("50–72", "LAB 3.1 — Básico: Deployment, ReplicaSet y self-healing"),
                ("72–90", "Conceptos: volúmenes, PV, PVC y StorageClass"),
                ("90–120", "LAB 3.2 — Intermedio: emptyDir, PV y PVC estáticos"),
                ("120–130", "Conceptos: StatefulSet y Headless Service"),
                ("130–158", "LAB 3.3 — Avanzado: almacenamiento por réplica"),
                ("158–176", "LAB 3.4 — Challenge: el PVC que nunca enlaza"),
                ("176–180", "Cierre, mental model de storage y CKA Tips"),
            ],
        },
        {
            "t": "section", "index": 1, "eyebrow": "Bloque 1",
            "title": "Controladores de workload",
            "subtitle": "Quién repara qué cuando algo se cae",
        },
        {
            "t": "chain",
            "eyebrow": "Relación",
            "heading": "Cada capa tiene una responsabilidad distinta",
            "theory": [
                "La cadena Deployment → ReplicaSet → Pod separa dos responsabilidades. El ReplicaSet gestiona CANTIDAD: cuenta cuántos Pods casan con su selector y crea o borra hasta llegar a spec.replicas. Es lo que da el self-healing: si borras un Pod, el ReplicaSet lo repone en segundos. Pero un ReplicaSet no sabe hacer rolling update; cambiarle la imagen solo afecta a los Pods que cree a partir de ese momento.",
                "El Deployment gestiona VERSIONES: cada vez que cambias spec.template (imagen, variables, recursos) crea un ReplicaSet nuevo y orquesta la transición gradual del viejo al nuevo. El ReplicaSet anterior no se borra, queda a 0 réplicas, y es lo que permite el rollback inmediato.",
                "kubectl scale toca spec.replicas, que vive en el ReplicaSet activo, así que NO genera un ReplicaSet nuevo. Y la pertenencia se puede comprobar en cualquier Pod leyendo metadata.ownerReferences, que apunta a su ReplicaSet, cuyo ownerReferences a su vez apunta al Deployment.",
            ],
            "nodes": ["Deployment", "ReplicaSet", "Pod"],
            "detail": {"label": "Quién hace qué", "lines": [
                "El Deployment gestiona VERSIONES: cada cambio en spec.template crea un ReplicaSet nuevo.",
                "El ReplicaSet gestiona CANTIDAD: cuenta los Pods que casan con su selector y ajusta.",
                "kubectl scale cambia spec.replicas, no spec.template: no genera un ReplicaSet nuevo.",
                "Un ReplicaSet NO hace rolling update: cambiar su imagen solo afecta a los Pods futuros.",
                "Compruébalo tú mismo: k get pod <p> -o jsonpath='{.metadata.ownerReferences}'",
            ]},
        },
        {
            "t": "cards",
            "eyebrow": "Elección",
            "heading": "Qué controlador para qué carga",
            "theory": [
                "El controlador elegido codifica las garantías que necesita la carga. El Deployment es para cargas stateless: réplicas intercambiables con nombre aleatorio (hash), sin orden de arranque, con rolling update y rollback. Es la opción por defecto para cualquier aplicación web o API.",
                "El StatefulSet es para cargas con estado que necesitan identidad: nombre estable y predecible (web-0, web-1…), arranque y parada en orden, y un volumen persistente propio por réplica creado mediante volumeClaimTemplates. Bases de datos, colas y clusters de consenso.",
                "El DaemonSet garantiza exactamente un Pod por nodo (agentes de logs, CNI, exporters de métricas); por eso drain necesita --ignore-daemonsets. El ReplicationController es el antecesor del ReplicaSet, solo referencia histórica. Y un Pod suelto no tiene ningún controlador detrás: si te importa que siga existiendo, no lo crees así.",
            ],
            "cols": 2,
            "cards": [
                {"title": "Deployment", "body": "Cargas stateless. Réplicas intercambiables, nombres con hash, rolling update y rollback. Es tu opción por defecto."},
                {"title": "StatefulSet", "body": "Cargas con estado. Nombre estable, orden garantizado y un volumen propio por réplica."},
                {"title": "DaemonSet", "body": "Un Pod por nodo: agentes, CNI, recolectores de logs. Por eso drain necesita --ignore-daemonsets."},
                {"title": "ReplicationController", "body": "Antecesor del ReplicaSet. Solo referencia histórica: no lo uses en nada nuevo."},
            ],
            "note": {"text": "Un Pod suelto no se autorrepara. Si te importa que siga existiendo, ponle un controlador detrás."},
        },
        {
            "t": "lab",
            "level": "Nivel básico",
            "title": "LAB 3.1 — Deployment, ReplicaSet y self-healing",
            "desc": "Ver con tus propios ojos la cadena de controladores y comprobar empíricamente qué garantiza cada uno.",
            "steps": [
                "Leer los ownerReferences de un Pod y de un ReplicaSet.",
                "Borrar un Pod y anotar qué controlador lo repone y en cuántos segundos.",
                "Escalar y comprobar que NO se crea un ReplicaSet nuevo. Explicar por qué.",
                "Crear un Pod huérfano con el label del selector y explicar qué le ocurre.",
                "Demostrar que un ReplicaSet no hace rolling update.",
            ],
            "file": "CLASE-03/LABORATORIOS/LAB-01-BASICO.md",
            "duration": "22 min",
            "validation": "k get deploy,rs,pods",
            "accent": "blue",
        },
        {
            "t": "section", "index": 2, "eyebrow": "Bloque 2",
            "title": "Almacenamiento",
            "subtitle": "Del directorio efímero al volumen que sobrevive al Pod",
        },
        {
            "t": "columns",
            "eyebrow": "Primera distinción",
            "heading": "emptyDir frente a almacenamiento persistente",
            "theory": [
                "Un volumen en Kubernetes comparte el ciclo de vida del POD, no el del contenedor: si un contenedor se reinicia dentro del mismo Pod, los datos del volumen siguen ahí. La diferencia clave está en qué pasa cuando el Pod se recrea.",
                "emptyDir se crea vacío cuando el Pod arranca en un nodo y se destruye cuando el Pod desaparece de ese nodo. Vive y muere con el Pod. Todos los contenedores del Pod lo comparten, así que es perfecto para caché, ficheros temporales o para pasar datos de un contenedor a otro (un init container prepara algo y el principal lo consume).",
                "PersistentVolume y PersistentVolumeClaim desacoplan el almacenamiento del Pod. El PV es el recurso real (un disco, un export NFS, un volumen de nube) y no tiene namespace. El PVC es la solicitud que hace la aplicación —tanto espacio, este modo de acceso— y sí vive en un namespace. El Pod nunca referencia el PV: monta el PVC. Es lo único que se debe usar para datos que importan.",
            ],
            "cols": [
                {"title": "emptyDir", "subtitle": "Vive y muere con el Pod", "lines": [
                    "Se crea vacío cuando el Pod arranca en un nodo.",
                    "Lo comparten todos los contenedores del Pod.",
                    "Si el Pod se recrea, el contenido se pierde.",
                    "Perfecto para caché, scratch y traspaso entre contenedores.",
                ]},
                {"title": "PersistentVolume + Claim", "subtitle": "Sobrevive al Pod", "accent": "ok", "lines": [
                    "El PV es el recurso; el PVC es la solicitud.",
                    "El PV no tiene namespace; el PVC sí.",
                    "El Pod nunca referencia el PV: referencia el PVC.",
                    "Es lo único que puedes usar para datos que importan.",
                ]},
            ],
            "note": {"text": "El volumen comparte el ciclo de vida del Pod, no el del contenedor: si un contenedor se reinicia, los datos siguen ahí."},
        },
        {
            "t": "chain",
            "eyebrow": "Relación",
            "heading": "De la clase de almacenamiento al contenedor",
            "theory": [
                "Hay dos caminos para que un PVC obtenga almacenamiento. En el aprovisionamiento ESTÁTICO, el administrador crea los PV a mano por adelantado; cuando aparece un PVC, el control plane busca un PV libre que encaje (mismo storageClassName, un accessMode compatible y capacidad suficiente) y los enlaza. Si no hay ninguno que encaje, el PVC se queda en Pending.",
                "En el aprovisionamiento DINÁMICO, el PVC nombra una StorageClass y el provisioner asociado crea el PV al vuelo con las características pedidas. Es lo habitual en la nube. Muchos clusters tienen una StorageClass marcada como default que se aplica a los PVC que no especifican ninguna.",
                "Dos trampas frecuentes: si existe una StorageClass por defecto y no la desactivas, tus PV estáticos se ignoran porque el PVC pide dinámico; y storageClassName: \"\" (cadena vacía) NO es lo mismo que omitir el campo —la cadena vacía desactiva explícitamente la clase por defecto y fuerza el emparejamiento estático.",
            ],
            "nodes": ["StorageClass", "PersistentVolume", "PersistentVolumeClaim", "Pod", "volumeMount"],
            "detail": {"label": "Dos caminos", "lines": [
                "ESTÁTICO: el administrador crea el PV a mano; el PVC lo encuentra si todo coincide.",
                "DINÁMICO: el PVC pide una StorageClass y el provisioner crea el PV al vuelo.",
                "Si hay StorageClass por defecto y no la desactivas, tus PV estáticos se ignoran.",
                'storageClassName: "" NO es lo mismo que omitir el campo: la cadena vacía desactiva la clase por defecto.',
            ]},
        },
        {
            "t": "table",
            "eyebrow": "Emparejamiento",
            "heading": "Un PV y un PVC enlazan solo si TODO esto coincide",
            "theory": [
                "El enlace (binding) entre un PVC y un PV es todo-o-nada: se comprueban varios criterios y basta que uno falle para que el PVC se quede en Pending. El storageClassName debe coincidir exactamente, incluida la cadena vacía. Los accessModes del PV deben OFRECER lo que el PVC PIDE (un PV solo-RWO no sirve para un PVC que pide RWX). La capacidad del PV debe ser mayor o igual que la solicitada.",
                "Si el PVC declara un selector de labels, el PV tiene que cumplirlo. Y el PV no puede estar ya reservado: si tiene un claimRef apuntando a otro PVC, no está disponible aunque su estado parezca libre.",
                "Un detalle que confunde en el examen: una vez enlazado, el PVC muestra la capacidad del PV real, no la que pidió. Si solicitas 1Gi y el único PV disponible es de 2Gi, verás 2Gi. Y cuando se borra el PVC, un PV con reclaimPolicy Retain no vuelve a Available: queda en Released con sus datos y su claimRef, y hay que liberarlo a mano.",
            ],
            "headers": ["Criterio", "Regla", "Si falla"],
            "weights": [3, 5, 3],
            "mono_last": False,
            "rows": [
                ["storageClassName", "Debe ser idéntico, incluida la cadena vacía", "PVC Pending"],
                ["accessModes", "El PV debe OFRECER lo que el PVC PIDE", "PVC Pending"],
                ["capacity", "El PV debe ser mayor o igual a lo solicitado", "PVC Pending"],
                ["selector (opcional)", "Si el PVC lo declara, los labels del PV deben cumplirlo", "PVC Pending"],
                ["claimRef", "El PV no puede estar ya reservado por otro claim", "PV en Released"],
            ],
            "note": {"text": "El PVC muestra la capacidad del PV enlazado, no la que pidió. Si pides 1Gi y recibes un PV de 2Gi, verás 2Gi."},
        },
        {
            "t": "concept",
            "eyebrow": "Modos y políticas",
            "heading": "Dos campos que deciden si tu Pod arranca",
            "theory": [
                "El accessMode describe cómo se puede montar el volumen. ReadWriteOnce (RWO) permite lectura y escritura desde un solo NODO —varios Pods de ese nodo pueden compartirlo— y es el modo por defecto de casi todo el almacenamiento de bloque. ReadOnlyMany (ROX) es solo lectura desde varios nodos. ReadWriteMany (RWX) es lectura y escritura desde varios nodos, y exige almacenamiento de fichero tipo NFS o CephFS. ReadWriteOncePod (RWOP) lo restringe a un único Pod, ni siquiera dos en el mismo nodo.",
                "El accessMode no es una propiedad mágica del disco: es lo que el PV declara ofrecer y el PVC declara necesitar. Pedir RWX sobre un backend que solo da RWO deja el PVC en Pending o el Pod sin arrancar.",
                "La reclaimPolicy decide qué pasa con el PV al borrar su PVC. Retain conserva el PV y sus datos en estado Released (recuperación manual). Delete borra el PV y el almacenamiento subyacente. Recycle fue eliminado hace tiempo: si lo ves en unos apuntes, están desactualizados.",
            ],
            "points": [
                "ReadWriteOnce (RWO): lectura y escritura desde un solo nodo. Es el modo por defecto de casi todo el almacenamiento de bloque.",
                "ReadOnlyMany (ROX): solo lectura desde varios nodos.",
                "ReadWriteMany (RWX): lectura y escritura desde varios nodos. Requiere almacenamiento de fichero, tipo NFS.",
                "ReadWriteOncePod (RWOP): un único Pod, ni siquiera dos en el mismo nodo.",
            ],
            "side": {"kind": "text", "title": "reclaimPolicy", "lines": [
                "Retain — al liberar el claim, el PV queda en Released con sus datos y su claimRef. No vuelve a estar disponible solo.",
                "Delete — se borran el PV y su almacenamiento.",
                "Recycle — ELIMINADO de Kubernetes. Si lo ves en un apunte, ese apunte es viejo.",
            ]},
        },
        {
            "t": "codeblocks",
            "eyebrow": "Aviso",
            "heading": "hostPath ata el Pod a un nodo concreto",
            "accent": "danger",
            "intro": "En un cluster multinodo, un PV con hostPath puede acabar montado en un nodo donde ese directorio no existe: el Pod arranca y ve un directorio vacío. Sirve para aprender, no para producción. La alternativa correcta es el tipo local con nodeAffinity, o un provisioner CSI.",
            "blocks": [
                {"lines": [
                    "# Liberar un PV que quedó en Released",
                    'k patch pv <pv> --type=json -p=\'[{"op":"remove","path":"/spec/claimRef"}]\'',
                ]},
            ],
        },
        {
            "t": "lab",
            "level": "Nivel intermedio",
            "title": "LAB 3.2 — emptyDir, PersistentVolume y PersistentVolumeClaim",
            "desc": "Compartir datos entre contenedores y aprovisionar almacenamiento estático, entendiendo por qué un PVC enlaza con un PV y no con otro.",
            "steps": [
                "Pod con dos contenedores compartiendo emptyDir. Demostrar que NO persiste.",
                "Dos PV de 2Gi distinguibles por label; forzar el enlace a uno concreto con selector.",
                "Comprobar por qué el PVC muestra 2Gi aunque pidió 1Gi.",
                "Borrar el PVC y explicar el estado Released.",
            ],
            "file": "CLASE-03/LABORATORIOS/LAB-02-INTERMEDIO.md",
            "duration": "30 min",
            "validation": "k get pv,pvc",
            "accent": "blue",
        },
        {
            "t": "section", "index": 3, "eyebrow": "Bloque 3",
            "title": "StatefulSets",
            "subtitle": "Cuando la identidad de cada réplica importa",
        },
        {
            "t": "cards",
            "eyebrow": "Garantías",
            "heading": "Qué te da un StatefulSet que un Deployment no",
            "theory": [
                "Un StatefulSet da cuatro garantías que un Deployment no puede ofrecer. Nombre estable: las réplicas se llaman <sts>-0, <sts>-1… sin hash, y si un Pod muere, el que lo sustituye recupera exactamente el mismo nombre. Orden garantizado: <sts>-1 no arranca hasta que <sts>-0 está Ready, y al reducir réplicas se retiran en orden inverso.",
                "Volumen propio: volumeClaimTemplates crea un PVC independiente por réplica (www-<sts>-0, www-<sts>-1…), de modo que cada Pod tiene su propio disco y nunca lo comparten. DNS por Pod: junto a un Headless Service (clusterIP: None), cada réplica es resoluble por <sts>-0.<svc>.<ns>.svc.cluster.local, lo que permite dirigirse a una instancia concreta.",
                "Un punto crítico de operación: los PVC creados por volumeClaimTemplates NO se borran al reducir réplicas ni al eliminar el StatefulSet. Es deliberado —son datos— y significa que recrear el StatefulSet reengancha los volúmenes existentes. El enlace que más se equivoca es serviceName, que debe coincidir con el nombre del Headless Service o el DNS por Pod no se crea, sin ningún error visible.",
            ],
            "cols": 2,
            "cards": [
                {"title": "Nombre estable", "body": "web-0, web-1, web-2. No hay hash. Si un Pod muere, el nuevo recupera exactamente el mismo nombre."},
                {"title": "Orden garantizado", "body": "web-1 no arranca hasta que web-0 está Ready. Al escalar hacia abajo, se retiran en orden inverso."},
                {"title": "Volumen propio", "body": "volumeClaimTemplates crea un PVC por réplica: www-web-0, www-web-1… No comparten disco."},
                {"title": "DNS por Pod", "body": "El Headless Service publica web-0.<svc>.<ns>.svc.cluster.local. Puedes dirigirte a una réplica concreta."},
            ],
            "note": {"text": "Los PVC creados por volumeClaimTemplates NO se borran al reducir réplicas ni al eliminar el StatefulSet. Es deliberado: son datos."},
        },
        {
            "t": "codeblocks",
            "eyebrow": "Sintaxis",
            "heading": "Las tres líneas que se equivocan siempre",
            "intro": "El enlace crítico: serviceName debe ser el nombre del Headless Service.",
            "blocks": [
                {"label": "El manifiesto", "lines": [
                    "apiVersion: v1",
                    "kind: Service",
                    "metadata: {name: nginx}",
                    "spec:",
                    "  clusterIP: None          # HEADLESS: sin VIP",
                    "  selector: {app: nginx}",
                    "  ports: [{name: web, port: 80}]",
                    "---",
                    "spec:",
                    "  serviceName: nginx       # <- debe coincidir con el Service de arriba",
                    "  volumeClaimTemplates:    # <- cuelga de spec, NO de spec.template",
                    "    - metadata: {name: www}",
                    "      spec:",
                    '        accessModes: ["ReadWriteOnce"]',
                    "        resources: {requests: {storage: 1Gi}}",
                ]},
            ],
            "note": {"text": "Si serviceName no coincide, el StatefulSet arranca igual pero el DNS por Pod no se crea. Fallo silencioso y muy frecuente."},
        },
        {
            "t": "lab",
            "level": "Nivel avanzado — solo requerimientos",
            "title": "LAB 3.3 — StatefulSet con identidad estable",
            "desc": "Desplegar una carga con estado que cumpla cuatro garantías, y demostrar cada una empíricamente.",
            "steps": [
                "Comprobar primero si hay StorageClass por defecto y decidir estático o dinámico.",
                "Headless Service + StatefulSet de 3 réplicas con un PVC de 1Gi cada una.",
                "Borrar web-1 y verificar que recupera nombre, PVC y datos.",
                "Escalar a 5 y volver a 3: explicar por qué sobreviven los PVC.",
                "Eliminar el StatefulSet, recrearlo y comprobar que los datos siguen ahí.",
            ],
            "file": "CLASE-03/LABORATORIOS/LAB-03-AVANZADO.md",
            "duration": "28 min",
            "validation": "k get sts,pvc",
            "accent": "blue",
        },
        {
            "t": "chain",
            "eyebrow": "Mental model",
            "heading": "Un PVC que no enlaza: ruta de diagnóstico",
            "nodes": ["PVC", "StorageClass", "PV", "AccessMode", "Capacity", "Pod"],
            "detail": {"label": "Pregunta en cada escalón", "lines": [
                "¿Coinciden los storageClassName? ¿Existe esa clase? ¿Hay una clase por defecto interfiriendo?",
                "¿Hay algún PV disponible? ¿En qué Phase está: Available, Bound o Released?",
                "¿El PVC pide un modo que ningún PV ofrece?",
                "¿El PV es al menos tan grande como lo solicitado?",
                "¿El claimName del Pod coincide con el PVC real?",
                "Y siempre: k describe pvc <pvc> | sed -n '/Events/,$p'",
            ]},
        },
        {
            "t": "lab",
            "level": "Challenge — el escenario arranca roto",
            "title": "LAB 3.4 — Challenge: el PVC que nunca enlaza",
            "desc": "Cuatro fallos: tres impiden el binding y el cuarto impide que el Pod arranque aunque el PVC ya esté Bound.",
            "steps": [
                "Prepara el escenario: RECURSOS/SCRIPTS/setup-lab.sh",
                "Hay PV distractores: aprende a descartar candidatos.",
                "Prohibido eliminar PersistentVolumes y prohibido crear una StorageClass por defecto.",
                "Objetivo: PVC Bound, Deployment 1/1 y /data escribible.",
            ],
            "file": "CLASE-03/LABORATORIOS/LAB-04-CHALLENGE.md",
            "duration": "20 min",
            "validation": "./validate-lab.sh",
            "accent": "danger",
        },
        {
            "t": "codeblocks",
            "eyebrow": "CKA Tip",
            "heading": "Los comandos que resuelven el 90 % del storage",
            "accent": "warn",
            "intro": "Una tabla de PV comparada con una de PVC responde casi cualquier pregunta de almacenamiento en menos de un minuto.",
            "blocks": [
                {"lines": [
                    "k get pv -o custom-columns=NAME:.metadata.name,CAP:.spec.capacity.storage,\\",
                    "MODES:.spec.accessModes,SC:.spec.storageClassName,PHASE:.status.phase",
                    "",
                    "k describe pvc <pvc> | sed -n '/Events/,$p'",
                    'k patch pv <pv> --type=json -p=\'[{"op":"remove","path":"/spec/claimRef"}]\'',
                ]},
            ],
        },
        {
            "t": "list",
            "eyebrow": "Checklist",
            "heading": "Comprueba que puedes hacer esto sin apuntes",
            "columns": 2,
            "style": "check",
            "items": [
                "Explico Deployment → ReplicaSet → Pod con ownerReferences.",
                "Demuestro el self-healing borrando un Pod.",
                "Comparto un directorio entre dos contenedores del mismo Pod.",
                "Creo un PV y un PVC que enlazan, y sé decir por qué enlazan.",
                "Enumero las cinco causas de un PVC en Pending.",
                "Distingo aprovisionamiento estático de dinámico.",
                "Explico Retain frente a Delete y libero un PV Released.",
                "Despliego un StatefulSet con Headless Service y volumeClaimTemplates.",
                "Demuestro que un Pod de StatefulSet recupera nombre y volumen.",
                "Sé por qué borrar un StatefulSet no borra sus PVC.",
            ],
        },
        {
            "t": "closing",
            "eyebrow": "Cierre de la clase",
            "title": "Clase 3 completada",
            "paragraphs": [
                "Ya sabes administrar cargas stateless y stateful, y darles almacenamiento que sobrevive.",
                "En la Clase 4 nos ocupamos del día a día de esas aplicaciones: actualizarlas sin cortar el servicio, revertirlas cuando salen mal, configurarlas desde fuera de la imagen y dimensionarlas.",
                "Repasa antes: la cadena Deployment → ReplicaSet → Pod.",
            ],
        },
    ],
}
