# -*- coding: utf-8 -*-
"""Contenido de la Clase 1 — Pods, YAML, Services y Scheduling.

El texto es el mismo del deck original; solo cambia la presentación.
"""

DECK = {
    "meta": {
        "clase_n": 1,
        "curso": "CKA Hands-On Training",
        "title": "Clase 1 — Pods, YAML, Services y Scheduling",
    },
    "slides": [
        {
            "t": "cover",
            "kicker": "CLASE 1",
            "title": "Pods, YAML, Services y Scheduling",
            "subtitle": "De ejecutar un comando a decidir dónde corre tu aplicación",
            "stats": [
                ("180 min", "Duración"),
                ("4", "Laboratorios"),
                ("70 %", "Práctica"),
                ("v1.35", "Kubernetes"),
            ],
        },
        {
            "t": "list",
            "eyebrow": "Objetivos",
            "heading": "Al terminar esta clase serás capaz de…",
            "columns": 1,
            "items": [
                "Crear Pods de forma imperativa y declarativa, y saber cuándo usar cada vía.",
                "Generar manifiestos en segundos con --dry-run=client -o yaml.",
                "Agrupar y seleccionar objetos con labels y selectors.",
                "Exponer aplicaciones con ClusterIP y NodePort.",
                "Explicar por qué un Service se queda sin endpoints, y repararlo.",
                "Controlar dónde se ejecuta un Pod: nodeSelector, taints, affinity, priority.",
                "Diagnosticar un Pod en estado Pending leyendo sus eventos.",
            ],
        },
        {
            "t": "agenda",
            "eyebrow": "180 minutos",
            "heading": "Agenda",
            "rows": [
                ("00–15", "Entorno, alias y atajos de examen"),
                ("15–45", "Conceptos: Pod, YAML, labels/selectors, Services"),
                ("45–65", "Demo: crear → inspeccionar → exponer → romper → reparar"),
                ("65–90", "LAB 1.1 — Básico: Pods, YAML e inspección"),
                ("90–120", "LAB 1.2 — Intermedio: Services, EndpointSlice y DNS"),
                ("120–128", "Conceptos: scheduling"),
                ("128–155", "LAB 1.3 — Avanzado: colocación de Pods"),
                ("155–175", "LAB 1.4 — Challenge: Pending y Service sin endpoints"),
                ("175–180", "Cierre, mental models y CKA Tips"),
            ],
        },
        {
            "t": "codeblocks",
            "eyebrow": "Antes de empezar",
            "heading": "Prepara tu shell. Hoy y en el examen.",
            "intro": "Estos cinco comandos ahorran entre 30 y 60 segundos por tarea. En un examen de dos horas, eso es media hora.",
            "blocks": [
                {"label": "En cada laboratorio", "lines": [
                    "alias k=kubectl",
                    "export do='--dry-run=client -o yaml'",
                    "export now='--force --grace-period=0'",
                    "source <(kubectl completion bash)",
                    "complete -o default -F __start_kubectl k",
                ]},
            ],
            "note": {"label": "Recuerda",
                     "text": "Escríbelos en cada laboratorio hasta que salgan sin pensar."},
        },
        {
            "t": "section",
            "index": 1,
            "eyebrow": "Bloque 1",
            "title": "El Pod",
            "subtitle": "La unidad mínima que Kubernetes programa y gestiona",
        },
        {
            "t": "concept",
            "eyebrow": "Concepto",
            "heading": "Qué es realmente un Pod",
            "theory": [
                "Un Pod es el objeto más pequeño que Kubernetes programa. Envuelve uno o varios contenedores que siempre se ejecutan juntos en el mismo nodo y que comparten una única IP, el espacio de puertos y los volúmenes; entre ellos se comunican por localhost. Es, a la vez, la unidad de scheduling, de escalado y de ciclo de vida: Kubernetes nunca coloca medio Pod ni escala contenedores sueltos.",
                "Un Pod es efímero y desechable por diseño. No se autorrepara: si el proceso muere de forma irrecuperable o el nodo se apaga, el Pod desaparece y nadie lo recrea. Por eso en producción casi nunca se crea un Pod suelto, sino mediante un controlador —Deployment, StatefulSet, DaemonSet o Job— que vigila el número deseado de réplicas y sustituye las que fallan.",
                "El patrón multicontenedor (init containers, sidecars, adapter, ambassador) se apoya justo en que todos comparten red y disco: un contenedor escribe en un volumen emptyDir y otro lo lee; un sidecar de proxy escucha en localhost. El contenedor principal aporta la función; los auxiliares la complementan sin acoplarse a su imagen.",
            ],
            "points": [
                "Es la unidad mínima de despliegue: uno o varios contenedores que comparten red y almacenamiento.",
                "Todos sus contenedores comparten la misma IP y el mismo espacio de puertos.",
                "Es efímero: si muere, no vuelve por sí solo. Quien lo repone es un controlador.",
                "Un Pod suelto no se autorrepara. Por eso en producción casi nunca se crean Pods sueltos.",
            ],
            "side": {"kind": "code", "title": "Anatomía mínima", "lines": [
                "apiVersion: v1",
                "kind: Pod",
                "metadata:",
                "  name: web",
                "  labels:",
                "    app: web",
                "spec:",
                "  containers:",
                "    - name: nginx",
                "      image: nginx:1.27-alpine",
                "      ports:",
                "        - containerPort: 80",
            ]},
        },
        {
            "t": "columns",
            "eyebrow": "Decisión",
            "heading": "Imperativo o declarativo",
            "theory": [
                "El modo imperativo ordena acciones concretas al API server (crea este Pod, escala a 3, cambia esta imagen). Es inmediato y no requiere escribir YAML, pero no deja constancia de la intención: el estado deseado solo vive en tu cabeza y en el cluster. Es ideal para tareas puntuales y para ir rápido en el examen.",
                "El modo declarativo describe en un manifiesto cómo debe quedar el recurso y deja que Kubernetes calcule las diferencias con kubectl apply. Es idempotente (aplicar dos veces no rompe nada), versionable en Git y reproducible entre entornos. Es lo que se usa en producción y lo que piden los enunciados cuando necesitan campos sin flag equivalente.",
                "En la práctica se combinan: se genera el esqueleto con un comando imperativo y --dry-run=client -o yaml, se edita el archivo para añadir lo que falta y se aplica con apply. Así se obtiene la velocidad del imperativo y la trazabilidad del declarativo.",
            ],
            "cols": [
                {"title": "Imperativo",
                 "subtitle": "Le dices a Kubernetes qué hacer",
                 "lines": [
                     "kubectl run · create · expose · scale · set image",
                     "Rapidísimo para tareas puntuales.",
                     "No deja rastro de la intención.",
                     "En el examen: úsalo siempre que puedas.",
                 ]},
                {"title": "Declarativo",
                 "subtitle": "Le dices cómo debe quedar",
                 "lines": [
                     "kubectl apply -f manifiesto.yaml",
                     "Idempotente y versionable en Git.",
                     "Es lo que se usa en producción.",
                     "En el examen: cuando el enunciado pide campos que no tienen flag.",
                 ]},
            ],
            "note": {"text": "El atajo que resuelve la tensión: genera con imperativo, edita el YAML, aplica con apply."},
        },
        {
            "t": "codeblocks",
            "eyebrow": "Demostración",
            "heading": "Crear, inspeccionar, entender",
            "blocks": [
                {"label": "Crear y ubicar", "lines": [
                    "k run web --image=nginx:1.27-alpine",
                    "k get pod web -o wide      # ¿en qué nodo? ¿qué IP?",
                ]},
                {"label": "Generar un manifiesto sin escribirlo", "lines": [
                    "k run api --image=httpd:2.4-alpine --port=80 $do > api.yaml",
                    "k explain pod.spec.terminationGracePeriodSeconds",
                ]},
                {"label": "Inspeccionar cuando algo va mal", "lines": [
                    "k describe pod web | sed -n '/Events/,$p'",
                    "k logs web            # contenedor actual",
                    "k logs web --previous # instancia anterior (CrashLoopBackOff)",
                ]},
            ],
            "note": {"text": "El 90 % de los diagnósticos empieza y termina en describe, events y logs."},
        },
        {
            "t": "table",
            "eyebrow": "Traducción",
            "heading": "El estado de un Pod ya te dice dónde mirar",
            "theory": [
                "El campo STATUS de un Pod no es decorativo: identifica la fase exacta en la que se detuvo el arranque, y cada fase se investiga con un comando distinto. Pending significa que el scheduler aún no le ha asignado nodo (recursos, taints o selectores); ContainerCreating y los errores de imagen o configuración ocurren ya en el nodo, durante la preparación del contenedor.",
                "CrashLoopBackOff indica que el contenedor arrancó y salió: la causa está en la instancia anterior, que solo se ve con kubectl logs --previous. Running con 0/1 READY quiere decir que el proceso vive pero su readinessProbe no pasa, así que el Pod queda fuera de los endpoints del Service. OOMKilled con exit 137 es memoria: el contenedor superó limits.memory y el kernel lo mató.",
                "Regla práctica: lee primero el estado, formula una hipótesis sobre la capa (scheduling, imagen, configuración, aplicación, recursos) y solo entonces ejecuta describe, events o logs para confirmarla. Esta tabla reaparece en la Clase 6 como base del método de diagnóstico.",
            ],
            "headers": ["Estado", "Significa", "Primer comando"],
            "weights": [3, 5, 4],
            "rows": [
                ["Pending", "El scheduler no encontró nodo", "describe pod → Events"],
                ["ContainerCreating", "Hay nodo; falla el volumen o la red", "describe pod → Events"],
                ["ImagePullBackOff", "El nodo no puede traer la imagen", "describe pod → Events"],
                ["CreateContainerConfigError", "Falta un ConfigMap, Secret o clave", "describe + get cm,secret"],
                ["CrashLoopBackOff", "El proceso arrancó y murió", "logs --previous"],
                ["Running 0/1 READY", "La readinessProbe falla", "describe pod → Conditions"],
            ],
            "note": {"text": "Volveremos a esta tabla en la Clase 6. Empieza a memorizarla hoy."},
        },
        {
            "t": "lab",
            "level": "Nivel básico",
            "title": "LAB 1.1 — Pods, YAML e inspección",
            "desc": "Crear Pods por las dos vías, generar manifiestos sin copiarlos y leer un Pod hasta entender por qué está o no está corriendo.",
            "steps": [
                "Namespace c1-basico y Pod web imperativo.",
                "Generar api.yaml con --dry-run=client -o yaml y añadirle labels y puerto nombrado.",
                "Filtrar Pods por label y localizar un campo con kubectl explain.",
                "Romper a propósito: imagen inexistente. Identificar el evento exacto.",
            ],
            "file": "CLASE-01/LABORATORIOS/LAB-01-BASICO.md",
            "duration": "25 min",
            "validation": "k get pods -o wide",
            "accent": "blue",
        },
        {
            "t": "section",
            "index": 2,
            "eyebrow": "Bloque 2",
            "title": "Services",
            "subtitle": "Cómo se alcanza un Pod cuando su IP cambia cada vez",
        },
        {
            "t": "concept",
            "eyebrow": "Concepto",
            "heading": "El problema que resuelve un Service",
            "theory": [
                "Las IP de los Pods son efímeras: cada recreación asigna una nueva, así que ningún cliente puede depender de ellas. Un Service resuelve esto dando un nombre DNS y una IP virtual (ClusterIP) estables a un conjunto de Pods. Esa ClusterIP no existe en ninguna interfaz de red; es una regla que kube-proxy programa en iptables o IPVS en todos los nodos y que reescribe el destino hacia un Pod concreto.",
                "El vínculo entre Service y Pods no es una lista fija: es un selector sobre labels que el controlador de endpoints evalúa continuamente. El resultado se materializa en objetos EndpointSlice, que contienen las IP y puertos de los Pods que además están Ready. Si un Pod deja de estar Ready, sale del EndpointSlice y deja de recibir tráfico sin que el Service cambie.",
                "Los tres puertos tienen significados distintos y confundirlos es el error más repetido: port es el puerto del Service, targetPort el del contenedor al que se reenvía, y nodePort el que se abre en cada nodo (rango 30000–32767) para los Services de tipo NodePort.",
            ],
            "points": [
                "Las IP de Pod son efímeras: cada recreación cambia la dirección.",
                "Un Service da un nombre y una IP estables a un conjunto de Pods.",
                "El vínculo no es una lista fija: es un selector sobre labels.",
                "El objeto que materializa ese vínculo es el EndpointSlice.",
            ],
            "side": {"kind": "text", "title": "Tres puertos, tres significados", "lines": [
                "port: el puerto del Service",
                "targetPort: el puerto del contenedor",
                "nodePort: el puerto publicado en cada nodo (30000–32767)",
                "Confundir port con targetPort es el error más repetido del curso",
            ]},
        },
        {
            "t": "chain",
            "eyebrow": "Relación",
            "heading": "La cadena que hay que memorizar",
            "theory": [
                "Esta cadena es el modelo mental para depurar cualquier problema de conectividad a un Service. El Service declara un selector; el controlador de endpoints busca los Pods cuyos labels lo cumplen y que están Ready, y escribe sus direcciones en el EndpointSlice; kube-proxy usa ese EndpointSlice para repartir el tráfico hacia la IP del Pod y su targetPort.",
                "Cuando el selector del Service y los labels del Pod no coinciden, el EndpointSlice queda vacío. El Service sigue existiendo, conserva su ClusterIP y sigue resolviéndose por DNS: lo único que falla es que no hay backends. El síntoma clásico es que nslookup del nombre funciona pero curl a la ClusterIP da timeout.",
                "Por eso el diagnóstico se hace de fuera hacia dentro: primero se comprueba que el nombre resuelve, luego que el EndpointSlice tiene direcciones (kubectl get endpointslices -l kubernetes.io/service-name=<svc>) y, si está vacío, se comparan selector y labels con kubectl get pods --show-labels.",
            ],
            "nodes": ["Service", "selector", "EndpointSlice", "Pod labels", "Pod : targetPort"],
            "detail": {"label": "Cuando se rompe", "lines": [
                "Si el selector no casa con los labels del Pod, el EndpointSlice queda vacío.",
                "El Service sigue existiendo, sigue teniendo ClusterIP y sigue resolviendo por DNS.",
                "Lo único que falla es que no hay backends a los que enviar el tráfico.",
                "Síntoma típico: nslookup funciona, curl da timeout.",
                "Diagnóstico: k get endpointslices -l kubernetes.io/service-name=<svc>",
            ]},
        },
        {
            "t": "cards",
            "eyebrow": "Tipos",
            "heading": "Qué tipo de Service usar",
            "theory": [
                "Los tipos de Service se apilan: cada uno añade una capa de exposición sobre el anterior. ClusterIP es la base y solo es accesible dentro del cluster; es lo que usan los componentes para hablar entre sí. NodePort añade a un ClusterIP la apertura del mismo puerto en todos los nodos, útil en laboratorio o detrás de un balanceador propio. LoadBalancer añade a un NodePort una IP externa que aprovisiona el proveedor de nube.",
                "ExternalName es la excepción: no crea IP ni endpoints ni proxy; CoreDNS simplemente devuelve un registro CNAME hacia un nombre externo. Sirve para dar un alias interno estable a un servicio de fuera del cluster.",
                "El caso especial es el Service headless (clusterIP: None): en lugar de una IP virtual, el DNS devuelve directamente las IP de todos los Pods del selector. Es la base de los StatefulSet, porque permite dirigirse a una réplica concreta por su nombre; se trata en la Clase 3.",
            ],
            "cols": 2,
            "cards": [
                {"title": "ClusterIP", "body": "Por defecto. Solo accesible dentro del cluster. Es lo que usas para que un componente hable con otro."},
                {"title": "NodePort", "body": "Abre el mismo puerto en todos los nodos, en el rango 30000–32767. Útil en laboratorio y detrás de un balanceador propio."},
                {"title": "LoadBalancer", "body": "Pide una IP pública al proveedor de nube. Una IP por Service: caro cuando hay muchos."},
                {"title": "ExternalName", "body": "No crea IP ni endpoints. CoreDNS devuelve un CNAME a un nombre externo."},
            ],
            "note": {"text": "Añade Headless (clusterIP: None) cuando necesites direccionar Pods individualmente: lo verás en la Clase 3."},
        },
        {
            "t": "codeblocks",
            "eyebrow": "Demostración",
            "heading": "Exponer, verificar y romper el selector",
            "blocks": [
                {"label": "Exponer", "lines": [
                    "k expose pod webserver --name=svc-web --port=8080 --target-port=80",
                    "k get svc,endpointslices",
                ]},
                {"label": "Romper deliberadamente", "lines": [
                    "k label pod webserver app=web-old --overwrite",
                    "k get endpointslices -l kubernetes.io/service-name=svc-web",
                    "# ADDRESSES vacío  ->  el curl deja de responder",
                ]},
                {"label": "Reparar sin destruir nada", "lines": [
                    "k label pod webserver app=webserver --overwrite",
                ]},
            ],
            "note": {"text": "Explicar → demostrar → practicar → romper → diagnosticar → corregir → validar. Es el método de todo el curso."},
        },
        {
            "t": "lab",
            "level": "Nivel intermedio",
            "title": "LAB 1.2 — Services, EndpointSlice y DNS",
            "desc": "Publicar un web y una base de datos, alcanzarlos por nombre, y provocar y reparar la pérdida de endpoints.",
            "steps": [
                "svc-dbserver ClusterIP 15432 → 5432 y svc-webserver NodePort 8080 → 80 con nodePort 31100.",
                "Resolver por DNS y hacer curl desde un Pod temporal.",
                "Acceder por NodePort desde fuera del cluster.",
                "Cambiar el label del Pod, observar el EndpointSlice vacío y repararlo sin recrear nada.",
            ],
            "file": "CLASE-01/LABORATORIOS/LAB-02-INTERMEDIO.md",
            "duration": "30 min",
            "validation": "k get endpointslices",
            "accent": "blue",
        },
        {
            "t": "section",
            "index": 3,
            "eyebrow": "Bloque 3",
            "title": "Scheduling",
            "subtitle": "Cómo decide Kubernetes dónde se ejecuta cada Pod",
        },
        {
            "t": "process",
            "eyebrow": "Proceso",
            "heading": "Cómo elige nodo el scheduler",
            "theory": [
                "El kube-scheduler observa los Pods sin nodo asignado y decide dónde colocarlos en dos etapas. En el filtrado descarta todos los nodos que no pueden alojar el Pod: no tienen recursos libres suficientes para los requests, no cumplen el nodeSelector o la node affinity obligatoria, tienen un taint que el Pod no tolera, o el puerto de host ya está ocupado.",
                "Con los nodos que superan el filtro pasa a la puntuación: asigna una nota a cada uno según la affinity preferida, el reparto de carga, la localidad de la imagen y otros criterios, y elige el de mayor puntuación. Finalmente vincula el Pod escribiendo spec.nodeName, y a partir de ahí el kubelet de ese nodo lo arranca.",
                "Si ningún nodo supera el filtrado, el Pod se queda en Pending y el scheduler emite un evento FailedScheduling que enumera cuántos nodos había y por qué falló cada uno. Ese mensaje es la respuesta, no una pista: hay que leerlo entero antes de tocar nada.",
            ],
            "steps": [
                {"title": "Filtrar", "body": "Descarta nodos que no cumplen: recursos, nodeSelector, taints, affinity required"},
                {"title": "Puntuar", "body": "Da una nota a los que quedan: affinity preferred, reparto de carga"},
                {"title": "Elegir", "body": "Se queda con el de mayor puntuación"},
                {"title": "Vincular", "body": "Escribe nodeName en el Pod y el kubelet lo arranca"},
            ],
            "note": {"text": "Si ningún nodo supera el filtrado, el Pod queda Pending y el evento FailedScheduling dice exactamente por qué. Ese evento es la respuesta, no una pista."},
        },
        {
            "t": "cards",
            "eyebrow": "Herramientas",
            "heading": "Cinco formas de influir en la colocación",
            "theory": [
                "Hay dos familias de mecanismos. Los que atraen o restringen por características del nodo: nodeSelector (igualdad exacta sobre labels de nodo, simple y suficiente casi siempre) y node affinity (lo mismo con operadores In, NotIn, Exists y una variante preferida que puntúa sin filtrar). Los taints hacen lo contrario: repelen; un nodo con un taint solo acepta Pods que lo toleren explícitamente, y la toleration únicamente levanta el veto, no atrae.",
                "Los que dependen de otros Pods: pod affinity y anti-affinity colocan o separan Pods según los labels de Pods ya existentes, usando topologyKey para definir el ámbito (mismo nodo, misma zona). Es como se reparten las réplicas de un Deployment por varios nodos.",
                "Y dos transversales: PriorityClass da preferencia a cargas críticas y permite desalojar (preemption) Pods de menor prioridad cuando no hay sitio; y los requests de recursos, que reservan capacidad: si el Pod no cabe en ningún nodo queda Pending, y esta es, con diferencia, la causa más frecuente.",
            ],
            "cols": 3,
            "cards": [
                {"title": "nodeSelector", "body": "Igualdad exacta sobre labels de nodo. Simple y suficiente el 80 % de las veces."},
                {"title": "Taints y Tolerations", "body": "El taint repele; la toleration solo levanta el veto. NO atrae."},
                {"title": "Node Affinity", "body": "Como nodeSelector pero con operadores, y con variante preferida que puntúa sin filtrar."},
                {"title": "Pod (Anti-)Affinity", "body": "Coloca o separa Pods según los labels de otros Pods. topologyKey define el ámbito."},
                {"title": "PriorityClass", "body": "Da preferencia a cargas críticas y permite desalojar (preemption) las de menor prioridad."},
                {"title": "Recursos", "body": "requests reserva capacidad. Si no cabe en ningún nodo, Pending. Es la causa más frecuente."},
            ],
        },
        {
            "t": "columns",
            "eyebrow": "Matiz crítico",
            "heading": "required frente a preferred",
            "theory": [
                "requiredDuringSchedulingIgnoredDuringExecution es una condición dura: forma parte del filtrado, así que si ningún nodo la cumple el Pod se queda en Pending. Equivale a un nodeSelector con operadores. Su estructura es una lista de nodeSelectorTerms, y dentro de cada término las matchExpressions se combinan con AND.",
                "preferredDuringSchedulingIgnoredDuringExecution es una preferencia blanda: interviene solo en la puntuación. Si ningún nodo la cumple, el Pod se programa igual en el mejor disponible. Su estructura es distinta: una lista de objetos {weight, preference}, donde weight (1–100) es cuánto suma a la nota del nodo. Nunca deja un Pod sin arrancar.",
                "El sufijo IgnoredDuringExecution significa que la regla solo se evalúa al programar: si más tarde cambian los labels del nodo, el Pod que ya está corriendo no se mueve. La contrapartida RequiredDuringExecution, que sí expulsaría Pods, aún no está implementada.",
            ],
            "cols": [
                {"title": "requiredDuringScheduling…", "tag": "Filtra", "accent": "blue",
                 "lines": [
                     "Si ningún nodo cumple, el Pod queda Pending.",
                     "Es una condición, no una preferencia.",
                     "Equivale a nodeSelector, con más operadores.",
                     "Es lo único que puede dejarte un Pod sin arrancar.",
                 ]},
                {"title": "preferredDuringScheduling…", "tag": "Puntúa", "accent": "warn",
                 "lines": [
                     "Si ningún nodo cumple, el Pod se programa igual.",
                     "Suma weight (1–100) a la puntuación del nodo.",
                     "Su estructura es distinta: lista de {weight, preference}.",
                     "Nunca deja un Pod en Pending.",
                 ]},
            ],
            "note": {"text": "IgnoredDuringExecution significa que si los labels del nodo cambian después, el Pod que ya corre se queda donde está."},
        },
        {
            "t": "codeblocks",
            "eyebrow": "Sintaxis",
            "heading": "Los fragmentos que hay que saber escribir",
            "blocks": [
                {"label": "nodeSelector y toleration", "lines": [
                    "nodeSelector: {environment: production}",
                    "",
                    "tolerations:",
                    "  - {key: team, operator: Equal, value: data, effect: NoSchedule}",
                ]},
                {"label": "Node affinity con regla obligatoria y preferida", "lines": [
                    "affinity:",
                    "  nodeAffinity:",
                    "    requiredDuringSchedulingIgnoredDuringExecution:",
                    "      nodeSelectorTerms:",
                    "        - matchExpressions:",
                    "            - {key: environment, operator: In, values: [production, staging]}",
                    "    preferredDuringSchedulingIgnoredDuringExecution:",
                    "      - weight: 60",
                    "        preference:",
                    "          matchExpressions:",
                    "            - {key: disktype, operator: In, values: [ssd]}",
                ]},
            ],
        },
        {
            "t": "chain",
            "eyebrow": "Mental model",
            "heading": "Un Pod en Pending: ruta de diagnóstico",
            "theory": [
                "Un Pod en Pending casi siempre es un problema de scheduling: el scheduler no ha encontrado ningún nodo que lo pueda alojar. El primer paso, sin excepción, es leer los eventos con kubectl describe pod <p> | sed -n '/Events/,$p'. El mensaje FailedScheduling indica cuántos nodos hay y agrupa el motivo de rechazo de cada uno.",
                "Ese mensaje suele señalar varias causas a la vez, por ejemplo: «0/3 nodes are available: 1 node(s) had untolerated taint, 2 node(s) didn't match node selector». Se revisan en este orden: recursos (¿los requests caben en algún nodo?), nodeSelector (¿existe un nodo con esos labels?), node affinity obligatoria, y taints frente a tolerations.",
                "Menos frecuente, pero posible: no hay ningún nodo Ready, o el Pod pide un hostPort ya ocupado. Lo que nunca se hace es adivinar y aplicar tres cambios seguidos: se corrige una causa, se vuelve a mirar el evento y se repite.",
            ],
            "nodes": ["Pod Pending", "Events", "Recursos (requests)", "nodeSelector", "Affinity", "Taints / Tolerations"],
            "detail": {"label": "Cómo se aplica", "lines": [
                "Empieza siempre por los eventos: el mensaje FailedScheduling enumera cuántos nodos hay y por qué falló cada uno.",
                "Ejemplo real: 0/3 nodes are available: 1 node(s) had untolerated taint, 2 node(s) didn't match node selector.",
                "Ese mensaje te está diciendo que hay dos causas distintas actuando a la vez.",
                "No adivines: k describe pod <p> | sed -n '/Events/,$p'",
            ]},
        },
        {
            "t": "lab",
            "level": "Nivel avanzado — solo requerimientos",
            "title": "LAB 1.3 — Colocación de Pods",
            "desc": "Resolver un escenario de colocación decidiendo tú los recursos, comandos, orden y validaciones. No hay solución paso a paso.",
            "steps": [
                "Reservar un nodo para el equipo de datos con un taint, y que solo un Pod pueda ir allí.",
                "Forzar una carga de producción con nodeSelector.",
                "Escribir nodeAffinity required + preferred con weight 60.",
                "Repartir réplicas con podAntiAffinity y provocar un FailedScheduling.",
                "Crear PriorityClasses y documentar un evento de preemption.",
            ],
            "file": "CLASE-01/LABORATORIOS/LAB-03-AVANZADO.md",
            "duration": "27 min",
            "validation": "k get nodes -L environment",
            "accent": "blue",
        },
        {
            "t": "lab",
            "level": "Challenge — el escenario arranca roto",
            "title": "LAB 1.4 — Challenge: la aplicación shop no responde",
            "desc": "Cuatro fallos encadenados, ninguno anunciado. Identificar, diagnosticar, corregir y validar sin borrar el Deployment ni el Service.",
            "steps": [
                "Prepara el escenario: RECURSOS/SCRIPTS/setup-lab.sh",
                "Documenta por cada fallo: síntoma, comando que lo reveló, causa raíz.",
                "Objetivo: 3/3 réplicas Running y curl http://<IP-worker>:31200 devuelve 200.",
                "Prohibido: eliminar y recrear. Repara in situ con edit, patch, set, label o scale.",
            ],
            "file": "CLASE-01/LABORATORIOS/LAB-04-CHALLENGE.md",
            "duration": "20 min",
            "validation": "./validate-lab.sh",
            "accent": "danger",
        },
        {
            "t": "codeblocks",
            "eyebrow": "CKA Tip",
            "heading": "Atajos que te devuelven minutos",
            "accent": "warn",
            "intro": "Ninguno de estos comandos es opcional en el examen. El nodePort no se puede fijar con expose: hay que generar el YAML y editarlo.",
            "blocks": [
                {"lines": [
                    "k run nginx --image=nginx --port=80 $do > pod.yaml",
                    "k create deployment web --image=nginx --replicas=3",
                    "k expose deployment web --port=80 --target-port=8080 --name=web-svc",
                    "k config set-context --current --namespace=<ns>   # deja de escribir -n",
                    "k get pods -A -o wide | grep -vE 'Running|Completed'",
                    "k taint node <n> key=value:NoSchedule   /   k taint node <n> key-",
                ]},
            ],
        },
        {
            "t": "list",
            "eyebrow": "Checklist",
            "heading": "Comprueba que puedes hacer esto sin apuntes",
            "columns": 2,
            "style": "check",
            "items": [
                "Creo un Pod imperativa y declarativamente.",
                "Genero YAML con --dry-run=client -o yaml.",
                "Uso kubectl explain para recordar un campo.",
                "Expongo un Pod con ClusterIP y con NodePort.",
                "Explico por qué un Service tiene 0 endpoints y lo reparo.",
                "Resuelvo un Service por DNS desde otro Pod.",
                "Fuerzo un Pod a un nodo con nodeSelector.",
                "Aplico y tolero un taint.",
                "Escribo nodeAffinity required y preferred.",
                "Diagnostico un FailedScheduling leyendo los eventos.",
            ],
        },
        {
            "t": "closing",
            "eyebrow": "Cierre de la clase",
            "title": "Clase 1 completada",
            "paragraphs": [
                "Ya sabes crear workloads, exponerlos y controlar dónde se ejecutan.",
                "En la Clase 2 bajamos un nivel: administrar el cluster que los sostiene. Upgrade de kubeadm, backup y restore de etcd, y control de acceso con RBAC.",
                "Repasa antes: kubectl explain, describe y la lectura de eventos.",
            ],
        },
    ],
}
