# -*- coding: utf-8 -*-
"""Contenido de la Clase 6 — Troubleshooting e Integración."""

DECK = {
    "meta": {
        "clase_n": 6,
        "curso": "CKA Hands-On Training",
        "title": "Clase 6 — Troubleshooting e Integración",
    },
    "slides": [
        {
            "t": "cover",
            "kicker": "CLASE 6",
            "title": "Troubleshooting e Integración",
            "subtitle": "El 30 % del examen y la razón por la que hiciste las cinco clases anteriores",
            "stats": [
                ("180 min", "Duración"),
                ("5", "Laboratorios"),
                ("30 %", "Peso en el CKA"),
                ("0", "Temas nuevos"),
            ],
        },
        {
            "t": "list",
            "eyebrow": "Objetivos",
            "heading": "Al terminar esta clase serás capaz de…",
            "columns": 1,
            "items": [
                "Aplicar un método de diagnóstico reproducible en vez de ir probando comandos.",
                "Reconocer cada estado de Pod y saber a qué capa apunta.",
                "Diagnosticar fallos de nodo y de control plane, no solo de aplicación.",
                "Resolver escenarios que cruzan scheduling, storage, configuración, permisos y red.",
                "Trabajar contrarreloj sin perder el método.",
                "Desplegar y reparar una arquitectura completa de principio a fin.",
            ],
        },
        {
            "t": "agenda",
            "eyebrow": "180 minutos",
            "heading": "Agenda",
            "rows": [
                ("00–12", "Método de diagnóstico y mapa de estados"),
                ("12–30", "Demo: cinco Pods rotos, cinco causas distintas, en 15 minutos"),
                ("30–50", "LAB 6.1 — Básico: identificar el estado y la capa"),
                ("50–78", "LAB 6.2 — Intermedio: nodo y control plane"),
                ("78–105", "LAB 6.3 — Avanzado: cadena de fallos entre capas"),
                ("105–120", "LAB 6.4 — Challenge: contrarreloj, 15 minutos"),
                ("120–170", "LAB 6.5 — INTEGRADOR FINAL"),
                ("170–178", "Checklist CKA y Cheat Sheet"),
                ("178–180", "Cierre del curso"),
            ],
        },
        {
            "t": "section", "index": 1, "eyebrow": "Bloque 1",
            "title": "El método",
            "subtitle": "Lo que separa a quien diagnostica de quien prueba comandos",
        },
        {
            "t": "process",
            "eyebrow": "Método general",
            "heading": "Seis pasos, siempre en el mismo orden",
            "steps": [
                {"title": "Observar", "body": "get: ¿qué estado exacto tiene cada objeto?"},
                {"title": "Acotar", "body": "¿En qué capa está el problema? No toques nada todavía."},
                {"title": "Hipótesis", "body": "Formula una causa concreta antes de investigar."},
                {"title": "Verificar", "body": "Un comando que la confirme o la descarte."},
                {"title": "Corregir", "body": "Una cosa cada vez."},
                {"title": "Validar", "body": "Comprobar antes de seguir."},
            ],
            "note": {"text": "El error de siempre: saltar de «observar» a «corregir». Se arreglan tres cosas a la vez, dos estaban bien, y ya nadie sabe qué pasaba."},
        },
        {
            "t": "table",
            "eyebrow": "Traducción",
            "heading": "El estado ya te dice en qué fase murió el Pod",
            "headers": ["Estado", "Fase en la que falló", "Primer comando"],
            "weights": [3, 4, 3],
            "rows": [
                ["Pending", "El scheduler no encontró nodo", "describe pod → Events"],
                ["ContainerCreating atascado", "Montaje de volumen o red del Pod", "describe pod → Events"],
                ["ImagePullBackOff", "El nodo no puede traer la imagen", "describe pod → Events"],
                ["CreateContainerConfigError", "Falta un ConfigMap, Secret o clave", "describe + get cm,secret"],
                ["CrashLoopBackOff", "El proceso arrancó y murió", "logs --previous"],
                ["Running con 0/1 READY", "La readinessProbe falla", "describe pod → Conditions"],
                ["OOMKilled · exit 137", "Superó limits.memory", "describe pod → Last State"],
            ],
            "note": {"text": "Pending e ImagePullBackOff se confunden constantemente. En Pending el Pod no tiene nodo; en ImagePullBackOff ya lo tiene."},
        },
        {
            "t": "codeblocks",
            "eyebrow": "El comando que más rinde",
            "heading": "logs --previous existe por una razón",
            "accent": "danger",
            "intro": "En un CrashLoopBackOff, kubectl logs devuelve el contenedor ACTUAL, que probablemente aún no ha escrito nada. La causa está en la instancia anterior. Quien no conoce --previous concluye que «no hay logs» y se queda sin diagnóstico.",
            "blocks": [
                {"lines": [
                    "k logs <pod> --previous",
                    "k describe pod <pod> | sed -n '/Events/,$p'",
                    "k describe pod <pod> | grep -A5 'Last State'",
                    "k get events -n <ns> --sort-by=.lastTimestamp | tail -20",
                    "k get pods -A -o wide | grep -vE 'Running|Completed'",
                ]},
            ],
        },
        {
            "t": "lab",
            "level": "Nivel básico",
            "title": "LAB 6.1 — Traducir estados: seis Pods, seis causas",
            "desc": "Convertir el estado de un Pod en una hipótesis ANTES de investigar, y confirmarla con un solo comando.",
            "steps": [
                "Rellenar la tabla de hipótesis mirando solo kubectl get pods.",
                "Confirmar cada caso con uno o dos comandos, no más.",
                "Usar logs --previous en el caso que lo requiere.",
                "Reparar atacando la causa, no el síntoma.",
            ],
            "file": "CLASE-06/LABORATORIOS/LAB-01-BASICO.md",
            "duration": "20 min",
            "validation": "./validate-lab.sh basico",
            "accent": "blue",
        },
        {
            "t": "section", "index": 2, "eyebrow": "Bloque 2",
            "title": "Nodo y control plane",
            "subtitle": "Cuando el problema está debajo de las aplicaciones",
        },
        {
            "t": "columns",
            "eyebrow": "Distinción crítica",
            "heading": "NotReady no es SchedulingDisabled",
            "cols": [
                {"title": "NotReady", "subtitle": "El nodo está averiado", "accent": "danger", "lines": [
                    "El kubelet no reporta al API server.",
                    "Causas: kubelet parado, runtime caído, disco lleno, red del nodo.",
                    "Se diagnostica por SSH: systemctl status kubelet, journalctl, df -h.",
                    "Los Pods que había ahí acaban siendo desalojados.",
                ]},
                {"title": "SchedulingDisabled", "subtitle": "El nodo está cerrado a propósito", "accent": "warn", "lines": [
                    "Alguien ejecutó cordon o drain y no lo revirtió.",
                    "El nodo está perfectamente sano.",
                    "Los Pods existentes siguen corriendo con normalidad.",
                    "Se arregla con un comando: kubectl uncordon.",
                ]},
            ],
            "note": {"text": "Confundirlos cuesta diez minutos revisando el kubelet de un nodo que no tiene absolutamente nada."},
        },
        {
            "t": "chain",
            "eyebrow": "Cuando kubectl no responde",
            "heading": "Deja de usar kubectl",
            "nodes": ["kubectl no responde", "systemctl status kubelet", "crictl ps -a",
                      "crictl logs / journalctl", "/etc/kubernetes/manifests/"],
            "detail": {"label": "Por qué funciona", "lines": [
                "El kubelet es un servicio de systemd, no un contenedor: sigue vivo aunque el API server esté caído.",
                "Sus logs registran por qué no consigue arrancar un static Pod. Es la fuente de verdad.",
                "crictl sustituye a kubectl para ver y depurar contenedores en el nodo.",
                "Editar el manifiesto en /etc/kubernetes/manifests/ hace que el kubelet recree el componente en segundos.",
                "No existe systemctl restart kube-apiserver: el API server es un contenedor que gestiona el kubelet.",
                "kubeadm guarda copias de seguridad en /etc/kubernetes/tmp/kubeadm-backup-manifests-*",
            ]},
        },
        {
            "t": "lab",
            "level": "Nivel intermedio",
            "title": "LAB 6.2 — Nodo y control plane",
            "desc": "Dos incidentes seguidos: un worker que no acepta Pods y un control plane que deja kubectl sin respuesta.",
            "steps": [
                "Distinguir NotReady de SchedulingDisabled leyendo las Conditions.",
                "Orden de diagnóstico: kubelet → runtime → disco.",
                "Diagnosticar el control plane SIN kubectl, con crictl y journalctl.",
                "Localizar el error del static Pod y esperar a que el kubelet lo recree.",
                "Prohibido reiniciar nodos como primera medida: esconde la causa.",
            ],
            "file": "CLASE-06/LABORATORIOS/LAB-02-INTERMEDIO.md",
            "duration": "28 min",
            "validation": "k get nodes -o wide",
            "accent": "blue",
        },
        {
            "t": "section", "index": 3, "eyebrow": "Bloque 3",
            "title": "Los seis mental models",
            "subtitle": "Todo el curso condensado en seis rutas de diagnóstico",
        },
        {
            "t": "cards",
            "eyebrow": "Referencia",
            "heading": "Cada capa tiene su ruta",
            "cols": 3,
            "cards": [
                {"title": "POD", "body": "get → describe → events → logs → logs --previous. El punto de partida de todo."},
                {"title": "SCHEDULING", "body": "Pending → Events → recursos → nodeSelector → affinity → taints."},
                {"title": "SERVICE", "body": "Service → selector → EndpointSlice → labels del Pod → targetPort."},
                {"title": "STORAGE", "body": "PVC → StorageClass → PV → accessMode → capacity → Pod."},
                {"title": "RBAC", "body": "identidad → Role/ClusterRole → binding → recurso → verbo → auth can-i."},
                {"title": "NETWORKING", "body": "Pod → Service → EndpointSlice → DNS → NetworkPolicy → Ingress."},
            ],
            "note": {"text": "No son mnemotecnias: son el orden en que hay que descartar causas. Saltarse un escalón es lo que hace perder tiempo."},
        },
        {
            "t": "chain",
            "eyebrow": "Cadenas de fallos",
            "heading": "Cuando todo parece roto, hay un orden",
            "nodes": ["PERMISOS", "SCHEDULING", "STORAGE", "CONFIGURACIÓN", "APLICACIÓN", "RED"],
            "detail": {"label": "Se diagnostica de abajo hacia arriba", "lines": [
                "Sin permisos no puedes ni operar: auth can-i primero.",
                "Sin nodo no hay Pod: un Pod Pending no puede tener un problema de red.",
                "Sin volumen el Pod no monta y se queda en ContainerCreating.",
                "Sin ConfigMap o Secret el contenedor ni siquiera se crea.",
                "Sin contenedor corriendo no hay nada que probar por red.",
                "Y solo entonces: DNS, endpoints, políticas e Ingress.",
            ]},
        },
        {
            "t": "lab",
            "level": "Nivel avanzado",
            "title": "LAB 6.3 — Cadena de fallos entre capas",
            "desc": "Seis fallos encadenados donde cada corrección destapa el siguiente. Obliga a recorrer todas las capas del curso.",
            "steps": [
                "Corregir los permisos de una ServiceAccount con mínimo privilegio.",
                "Levantar un StatefulSet de 3 réplicas con volumen escribible.",
                "Hacer llegar configuración y credenciales al contenedor.",
                "Conseguir que el DNS por Pod resuelva.",
                "Justificar por escrito el orden en que atacaste los fallos.",
            ],
            "file": "CLASE-06/LABORATORIOS/LAB-03-AVANZADO.md",
            "duration": "27 min",
            "validation": "./validate-lab.sh cadena",
            "accent": "blue",
        },
        {
            "t": "lab",
            "level": "Challenge — cronometrado",
            "title": "LAB 6.4 — Challenge contrarreloj: 15 minutos",
            "desc": "Cinco tareas con peso distinto y tiempo insuficiente. Reproduce exactamente la presión del examen.",
            "steps": [
                "Minuto 0–1: lee las cinco tareas y ordénalas. No empieces por la primera.",
                "Ataca lo de mayor peso que sepas resolver rápido.",
                "Si una tarea pasa de 4 minutos, déjala y vuelve al final.",
                "Valida cada tarea al terminarla: «casi hecha» puntúa cero.",
                "Objetivo: 24 de 35 puntos, el 66 % de aprobado del CKA.",
            ],
            "file": "CLASE-06/LABORATORIOS/LAB-04-CHALLENGE.md",
            "duration": "15 min",
            "validation": "./validate-lab.sh sprint",
            "accent": "danger",
        },
        {
            "t": "section", "index": 4, "eyebrow": "Bloque 4",
            "title": "Laboratorio integrador final",
            "subtitle": "Construir la arquitectura completa y después repararla",
        },
        {
            "t": "cards",
            "eyebrow": "Arquitectura a construir",
            "heading": "Todo el curso en un solo despliegue",
            "cols": 2,
            "cards": [
                {"title": "INGRESS", "body": "HTTPS con certificado propio, host tienda.local, dos paths."},
                {"title": "FRONTEND", "body": "Deployment 2 réplicas, readiness, requests y limits."},
                {"title": "BACKEND", "body": "ConfigMap por envFrom, Secret por variable y como volumen."},
                {"title": "STATEFULSET", "body": "3 réplicas postgres, Headless Service, un PVC RWO por réplica."},
            ],
            "note": {"text": "Más NetworkPolicies con default deny que solo permiten DNS, frontend→backend, backend→db y la entrada del Ingress Controller. Se construye SIN manifiestos dados: solo a partir de requerimientos."},
        },
        {
            "t": "codeblocks",
            "eyebrow": "Orden de construcción",
            "heading": "Las políticas de red, siempre al final",
            "accent": "danger",
            "intro": "Si aplicas default-deny antes de que las aplicaciones funcionen, nada arranca y el diagnóstico se vuelve imposible: no sabrás si el problema es la red o el despliegue. Construye, valida, y solo entonces cierra la red.",
            "blocks": [
                {"lines": [
                    "Namespace -> ConfigMap + Secret -> Storage -> StatefulSet -> Deployments",
                    "   -> Services -> TLS -> Ingress -> NetworkPolicies -> Validación",
                ]},
            ],
            "note": {"text": "Otros puntos de fricción esperados: PGDATA en un subdirectorio, el namespace del Ingress Controller, y anti-affinity preferred en vez de required con solo dos nodos."},
        },
        {
            "t": "lab",
            "level": "Integrador — construcción y troubleshooting",
            "title": "LAB 6.5 — INTEGRADOR FINAL — Fase 1 y Fase 2",
            "desc": "30 minutos para construir la arquitectura desde requerimientos. Después el instructor inyecta fallas y tienes 20 para repararla.",
            "steps": [
                "Fase 1: construir sin manifiestos dados y superar la validación completa.",
                "Fase 2: ./inject-failures.sh introduce entre 5 y 8 fallas. No se te dice cuáles.",
                "Documentar por cada falla: capa, síntoma, comando, causa raíz, corrección.",
                "Prohibido borrar el namespace, la política default-deny o los PVC.",
                "Los datos de la base de datos deben conservarse.",
            ],
            "file": "CLASE-06/LABORATORIOS/LAB-05-INTEGRADOR-FINAL.md",
            "duration": "50 min",
            "validation": "./validate-lab.sh final",
            "accent": "blue",
        },
        {
            "t": "codeblocks",
            "eyebrow": "Cierre",
            "heading": "Los cinco comandos que resuelven la mayoría de los incidentes",
            "intro": "En este orden, sin saltarse ninguno.",
            "blocks": [
                {"lines": [
                    "k -n <ns> get all,pvc,ingress,networkpolicy      # ¿qué hay y en qué estado?",
                    "k -n <ns> get events --sort-by=.lastTimestamp | tail -30",
                    "k -n <ns> describe pod <p> | sed -n '/Events/,$p'",
                    "k -n <ns> get endpointslices",
                    "k logs <p> --previous",
                ]},
            ],
            "note": {"text": "El método vale más que los comandos. Acota la capa antes de tocar nada, corrige una cosa cada vez, y valida antes de seguir. Es igual en el examen que a las tres de la mañana en producción."},
        },
        {
            "t": "list",
            "eyebrow": "Estrategia de examen",
            "heading": "Lo que hay que hacer el día del CKA",
            "columns": 2,
            "items": [
                "Primer minuto: lee todas las tareas y anota su peso.",
                "Ordénalas: primero las que valen mucho y sabes hacer rápido.",
                "Prepara alias k, export do y export now antes de la primera tarea.",
                "Cambia el contexto y el namespace que indica cada enunciado.",
                "Marca y salta cualquier tarea que se pase de tu presupuesto de tiempo.",
                "Valida cada tarea nada más terminarla.",
                "Guarda los últimos 10 minutos para las tareas marcadas.",
                "Usa solo kubernetes.io/docs y kubectl explain. Practica así desde hoy.",
            ],
        },
        {
            "t": "closing",
            "eyebrow": "Cierre del curso",
            "title": "Curso completado — 18 horas",
            "paragraphs": [
                "Has recorrido el camino completo: COMPRENDER → EJECUTAR → PRACTICAR → INTEGRAR → DIAGNOSTICAR → RESOLVER.",
                "Llévate dos documentos: 02-CHECKLIST-CKA.md para saber qué dominas de verdad, y 03-CHEATSHEET-CKA.md para repasar antes del examen.",
                "Y una recomendación: repite el LAB 6.5 completo una vez por semana hasta que te salga sin mirar. Es el mejor simulacro que tienes.",
            ],
        },
    ],
}
