# -*- coding: utf-8 -*-
"""Contenido de la Clase 4 — Lifecycle, ConfigMaps, Secrets y Recursos."""

DECK = {
    "meta": {
        "clase_n": 4,
        "curso": "CKA Hands-On Training",
        "title": "Clase 4 — Lifecycle, ConfigMaps, Secrets y Recursos",
    },
    "slides": [
        {
            "t": "cover",
            "kicker": "CLASE 4",
            "title": "Lifecycle, ConfigMaps, Secrets y Recursos",
            "subtitle": "Actualizar sin cortar, revertir sin drama, configurar desde fuera de la imagen",
            "stats": [
                ("180 min", "Duración"),
                ("4", "Laboratorios"),
                ("15 %", "Workloads en el CKA"),
                ("v0.8.1", "Metrics Server"),
            ],
        },
        {
            "t": "list",
            "eyebrow": "Objetivos",
            "heading": "Al terminar esta clase serás capaz de…",
            "columns": 1,
            "items": [
                "Ejecutar un Rolling Update controlado y seguir su progreso.",
                "Consultar el historial de revisiones y volver a una anterior.",
                "Detectar un despliegue defectuoso antes de que afecte a todas las réplicas.",
                "Externalizar configuración con ConfigMaps: variables, envFrom y volumen.",
                "Gestionar datos sensibles con Secrets, y explicar qué protegen y qué no.",
                "Definir requests y limits, y deducir la clase de QoS resultante.",
                "Instalar Metrics Server y medir el consumo real frente al solicitado.",
            ],
        },
        {
            "t": "agenda",
            "eyebrow": "180 minutos",
            "heading": "Agenda",
            "rows": [
                ("00–12", "Repaso de la Clase 3 y objetivos"),
                ("12–32", "Conceptos: rollout, revisiones, rollback, estrategias"),
                ("32–48", "Demo: rollout con imagen rota y rollout undo en vivo"),
                ("48–72", "LAB 4.1 — Básico: Rolling Update y Rollback"),
                ("72–90", "Conceptos: ConfigMaps y Secrets"),
                ("90–120", "LAB 4.2 — Intermedio: configuración externalizada"),
                ("120–132", "Conceptos: requests, limits, QoS y Metrics Server"),
                ("132–158", "LAB 4.3 — Avanzado: recursos, escalado y métricas"),
                ("158–176", "LAB 4.4 — Challenge: el despliegue que no arranca"),
                ("176–180", "Cierre y CKA Tips"),
            ],
        },
        {
            "t": "section", "index": 1, "eyebrow": "Bloque 1",
            "title": "Rolling Update y Rollback",
            "subtitle": "Cambiar la versión sin que nadie se entere",
        },
        {
            "t": "process",
            "eyebrow": "Mecánica",
            "heading": "Qué ocurre durante un Rolling Update",
            "theory": [
                "Un Rolling Update no reemplaza los Pods de golpe. Al cambiar spec.template el Deployment crea un ReplicaSet nuevo con 0 réplicas y luego hace un escalado cruzado: sube el nuevo de uno en uno y baja el viejo, manteniendo en todo momento un número de réplicas dentro de los márgenes que fijan maxSurge y maxUnavailable.",
                "maxSurge es cuántos Pods de más se permiten por encima del total deseado; maxUnavailable, cuántos de menos. Con los valores por defecto (25 %) y 3 réplicas, maxSurge redondea a 1 Pod extra y maxUnavailable a 0 indisponibles, así que el rollout es muy conservador: siempre hay 3 sirviendo.",
                "Un Pod nuevo solo CUENTA como disponible cuando su readinessProbe pasa. Por eso, si la imagen nueva está rota y nunca llega a Ready, el rollout se BLOQUEA en lugar de tumbar el servicio: las réplicas viejas siguen atendiendo. Al terminar, el ReplicaSet viejo queda a 0 réplicas pero no se borra —es el material del rollback.",
            ],
            "steps": [
                {"title": "Cambio", "body": "Modificas spec.template: se crea un ReplicaSet nuevo con 0 réplicas."},
                {"title": "Escalado cruzado", "body": "El nuevo sube, el viejo baja, respetando maxSurge y maxUnavailable."},
                {"title": "Readiness", "body": "Un Pod nuevo solo cuenta cuando su readinessProbe pasa."},
                {"title": "Completo", "body": "El ReplicaSet viejo queda a 0 réplicas, pero no se borra: es tu rollback."},
            ],
            "note": {"text": "Con 3 réplicas y los valores por defecto (25 %), maxSurge redondea a 1 Pod extra y maxUnavailable redondea a 0 indisponibles. Por eso el rollout es tan conservador."},
        },
        {
            "t": "concept",
            "eyebrow": "Concepto clave",
            "heading": "Un despliegue roto no debería tumbar el servicio",
            "theory": [
                "El comportamiento correcto ante un despliegue defectuoso es que el rollout se detenga, no que caiga el servicio. Si la imagen nueva no existe o el proceso no arranca, el Pod nuevo nunca llega a Ready. Con maxUnavailable en 0, el controlador no puede retirar ninguna réplica vieja hasta tener una nueva lista, así que el rollout se queda a la espera y las réplicas buenas siguen sirviendo indefinidamente.",
                "El síntoma es claro: kubectl rollout status se queda en «Waiting for deployment … X out of N new replicas have been updated» y no termina nunca. La solución inmediata es kubectl rollout undo, que vuelve a la revisión anterior.",
                "Todo esto depende de tener una readinessProbe. Sin ella, Kubernetes considera «listo» a cualquier Pod que arranque su proceso, aunque la aplicación aún no responda o esté rota; entonces sí entra en el Service, empieza a recibir tráfico y el servicio se degrada. La readinessProbe es lo que convierte un rollout peligroso en uno seguro.",
            ],
            "points": [
                "Si la imagen nueva no existe, el Pod nuevo nunca llega a Ready.",
                "Con maxUnavailable en 0, el controlador no puede retirar ninguna réplica vieja hasta que una nueva esté lista.",
                "Resultado: el rollout se BLOQUEA y las réplicas buenas siguen sirviendo. Eso es lo correcto.",
                "Sin readinessProbe, un Pod que arranca se considera listo aunque la aplicación no responda: ahí sí cae el servicio.",
            ],
            "side": {"kind": "code", "title": "Síntoma de rollout bloqueado", "lines": [
                "$ k rollout status deploy/web",
                "Waiting for deployment",
                '  "web" rollout to finish:',
                "  1 out of 3 new replicas",
                "  have been updated...",
                "",
                "# y no termina nunca",
                "",
                "$ k rollout undo deploy/web",
            ]},
        },
        {
            "t": "codeblocks",
            "eyebrow": "Actualización técnica",
            "heading": "--record ya no existe",
            "accent": "warn",
            "intro": "La opción --record fue eliminada de kubectl. La causa del cambio se registra ahora con una anotación, y hay que ponerla junto al cambio para que quede asociada a la revisión correcta.",
            "blocks": [
                {"lines": [
                    "k set image deploy/web nginx=nginx:1.27-alpine",
                    'k annotate deploy/web kubernetes.io/change-cause="Actualizacion a 1.27" --overwrite',
                    "",
                    "k rollout history deploy/web",
                    "k rollout history deploy/web --revision=3",
                    "k rollout undo    deploy/web --to-revision=1",
                ]},
            ],
            "note": {"text": "rollout undo no borra revisiones: crea una nueva con el contenido de la antigua. Por eso el contador sigue subiendo."},
        },
        {
            "t": "lab",
            "level": "Nivel básico",
            "title": "LAB 4.1 — Rolling Update y Rollback",
            "desc": "Llevar una aplicación por tres versiones, meter la pata a propósito en la cuarta y recuperarse sin caída de servicio.",
            "steps": [
                "Tres actualizaciones de imagen con su causa de cambio anotada.",
                "Observar en otra terminal la convivencia de dos ReplicaSets.",
                "Desplegar nginx:1.99-inexistente y explicar por qué NO cae el servicio.",
                "rollout undo y rollout undo --to-revision=1.",
                "Configurar revisionHistoryLimit y explicar su efecto.",
            ],
            "file": "CLASE-04/LABORATORIOS/LAB-01-BASICO.md",
            "duration": "24 min",
            "validation": "k rollout history",
            "accent": "blue",
        },
        {
            "t": "section", "index": 2, "eyebrow": "Bloque 2",
            "title": "ConfigMaps y Secrets",
            "subtitle": "Sacar la configuración fuera de la imagen",
        },
        {
            "t": "table",
            "eyebrow": "Decisión de diseño",
            "heading": "Cuatro formas de consumir, dos comportamientos",
            "theory": [
                "Un ConfigMap o un Secret se puede consumir de cuatro maneras, y lo que decide cuál usar es si el valor debe poder recargarse sin reiniciar el Pod. Las tres formas basadas en variables de entorno —env con configMapKeyRef o secretKeyRef para claves sueltas, y envFrom para volcar todas las claves de golpe— fijan el valor en el arranque del contenedor y NO se actualizan en caliente. Cambiar el ConfigMap no afecta a los Pods que ya corren.",
                "Montar el ConfigMap o el Secret como VOLUMEN sí propaga los cambios: el kubelet actualiza los ficheros del volumen al cabo de un tiempo, sin recrear el Pod. Por eso los archivos de configuración y los certificados se montan como volumen, y las variables simples se pasan como env.",
                "Para forzar que una variable de entorno tome el valor nuevo hay que provocar una recreación de los Pods, típicamente con kubectl rollout restart deployment/<d>. Y un Secret montado como volumen se guarda en un tmpfs (memoria), nunca en el disco del nodo.",
            ],
            "headers": ["Forma de consumo", "¿Se actualiza en caliente?", "Cuándo usarla"],
            "weights": [4, 3, 4],
            "mono_last": False,
            "rows": [
                ["env + configMapKeyRef", "No", "Una o dos claves concretas"],
                ["env + secretKeyRef", "No", "Una credencial concreta"],
                ["envFrom", "No", "Todas las claves de golpe"],
                ["Volumen (configMap o secret)", "Sí", "Archivos de configuración, certificados"],
            ],
            "note": {"text": "Si algo debe recargarse sin reiniciar el Pod, móntalo como volumen. Si no, usa variables. Para que una variable tome el valor nuevo: kubectl rollout restart."},
        },
        {
            "t": "concept",
            "eyebrow": "Corrección conceptual",
            "heading": "Un Secret no cifra nada",
            "theory": [
                "El contenido de un Secret se guarda en base64, que es una CODIFICACIÓN, no un cifrado: cualquiera con acceso al objeto puede decodificarlo con base64 -d. Un Secret y un ConfigMap son, en cuanto a confidencialidad del valor en sí, prácticamente lo mismo.",
                "Lo que aporta un Secret es otra cosa. Primero, es un tipo de objeto separado sobre el que se pueden dar permisos RBAC distintos: puedes permitir leer ConfigMaps a mucha gente y restringir los Secrets a unos pocos. Segundo, si el cluster tiene configurado EncryptionConfiguration, los Secrets (y solo ellos) se cifran en reposo dentro de etcd. Tercero, al montarse en tmpfs y no en la imagen, no se distribuye a todos los nodos ni queda en el registro de contenedores.",
                "En resumen: la protección de un Secret está en el control de acceso y en la configuración del cluster, no en el base64. Tratarlo como si el base64 fuera seguro es el malentendido más común.",
            ],
            "points": [
                "El contenido de un Secret está en base64, que es codificación reversible por cualquiera con acceso al objeto.",
                "Lo que protege un Secret es otra cosa: el acceso al objeto vía RBAC.",
                "Y, si está configurado, el cifrado en reposo de etcd (EncryptionConfiguration).",
                "Y el hecho de no estar dentro de la imagen del contenedor, que se distribuye a todas partes.",
            ],
            "side": {"kind": "code", "title": "Compruébalo en clase", "lines": [
                "k get secret db-cred -o yaml",
                "",
                "k get secret db-cred \\",
                "  -o jsonpath='{.data.password}' \\",
                "  | base64 -d; echo",
                "",
                "# -> Sup3rS3cret",
                "",
                "# Montado como volumen:",
                "k exec pod -- mount | grep cred",
                "# tmpfs ... (ro)  -> en memoria",
            ]},
        },
        {
            "t": "codeblocks",
            "eyebrow": "Imperativo",
            "heading": "Crear y consumir sin escribir YAML a mano",
            "blocks": [
                {"label": "Crear", "lines": [
                    "k create configmap app-config --from-literal=APP_COLOR=blue --from-literal=APP_MODE=prod",
                    "k create configmap web-html --from-file=index.html=web-moon.html",
                    "k create configmap vars --from-env-file=vars.env",
                    "k create secret generic db-cred --from-literal=user=admin --from-literal=password=x",
                    "k create secret tls secure-ingress --cert=cert.pem --key=key.pem",
                ]},
                {"label": "Consumir", "lines": [
                    "envFrom: [{configMapRef: {name: app-config}}]",
                    "env:",
                    "  - name: DB_PASSWORD",
                    "    valueFrom: {secretKeyRef: {name: db-cred, key: password}}",
                    "volumeMounts:",
                    "  - {name: cred, mountPath: /etc/db-cred, readOnly: true}",
                ]},
            ],
            "note": {"text": "--from-file=web-moon.html crea la clave 'web-moon.html'. Para que la clave sea index.html: --from-file=index.html=web-moon.html"},
        },
        {
            "t": "lab",
            "level": "Nivel intermedio",
            "title": "LAB 4.2 — ConfigMaps y Secrets",
            "desc": "Sacar de la imagen el index.html, los parámetros de la aplicación y la contraseña de la base de datos.",
            "steps": [
                "ConfigMap desde literales y desde archivo, con la clave correcta.",
                "Consumo con envFrom y como volumen montado que nginx sirve.",
                "Secret consumido por secretKeyRef y montado en solo lectura. Identificar el tmpfs.",
                "Cambiar ambos y comprobar qué se actualiza solo y qué no.",
            ],
            "file": "CLASE-04/LABORATORIOS/LAB-02-INTERMEDIO.md",
            "duration": "30 min",
            "validation": "k exec deploy/web-moon -- env",
            "accent": "blue",
        },
        {
            "t": "section", "index": 3, "eyebrow": "Bloque 3",
            "title": "Recursos y métricas",
            "subtitle": "Cuánto reservas, cuánto usas y qué pasa cuando te pasas",
        },
        {
            "t": "columns",
            "eyebrow": "Concepto",
            "heading": "requests y limits actúan en momentos distintos",
            "theory": [
                "requests y limits parecen dos caras de lo mismo, pero actúan en momentos distintos y los usan actores distintos. Los REQUESTS los usa el SCHEDULER: son la cantidad de CPU y memoria que el Pod reserva, y con ellos decide en qué nodo cabe. Si la suma de requests no cabe en ningún nodo, el Pod se queda en Pending con el evento «Insufficient cpu/memory». El fallo ocurre ANTES de arrancar.",
                "Los LIMITS los aplica el RUNTIME mediante cgroups, ya con el contenedor en ejecución: son el techo que no puede superar. La CPU es un recurso comprimible: pasarse del límite provoca throttling (el proceso va más lento), no muerte. La memoria NO es comprimible: superar limits.memory provoca que el kernel mate el contenedor con OOMKilled y exit code 137.",
                "La consecuencia para el diagnóstico es que Pending por CPU y OOMKilled por memoria son ramas completamente separadas: una se investiga en los eventos del scheduler, la otra en el Last State del contenedor. Y cuidado: si defines solo limits, Kubernetes copia esos valores a los requests y el Pod acaba en QoS Guaranteed sin que lo pretendieras.",
            ],
            "cols": [
                {"title": "requests", "subtitle": "Los usa el SCHEDULER", "lines": [
                    "Deciden en qué nodo cabe el Pod.",
                    "Reservan capacidad aunque no se consuma.",
                    "Si no caben en ningún nodo: Pending + Insufficient cpu.",
                    "El fallo ocurre ANTES de arrancar.",
                ]},
                {"title": "limits", "subtitle": "Los aplica el RUNTIME (cgroups)", "accent": "warn", "lines": [
                    "Ponen un techo al contenedor en ejecución.",
                    "CPU es comprimible: superar el límite provoca throttling, no muerte.",
                    "Memoria NO es comprimible: superarla provoca OOMKilled, exit 137.",
                    "El fallo ocurre DURANTE la ejecución.",
                ]},
            ],
            "note": {"text": "Pending por CPU y OOMKilled por memoria son ramas de diagnóstico completamente distintas. Confundirlas cuesta minutos que no tienes."},
        },
        {
            "t": "cards",
            "eyebrow": "QoS",
            "heading": "Tu configuración decide quién muere primero",
            "theory": [
                "La clase de QoS de un Pod no se declara: Kubernetes la deduce de cómo hayas puesto requests y limits, y determina el orden en que se desalojan los Pods cuando un nodo se queda sin memoria. Guaranteed exige que requests sea igual a limits en TODOS los recursos de TODOS los contenedores; es el último en ser desalojado.",
                "Burstable es cualquier Pod que tenga algún request o limit pero no cumpla la condición de Guaranteed. Es el caso más habitual en producción. BestEffort es un Pod sin ningún request ni limit: es el PRIMERO en caer cuando hay presión de memoria.",
                "La regla práctica: para cargas críticas, pon requests == limits y consigue Guaranteed; para el resto, define al menos requests realistas para no acabar en BestEffort. Y recuerda que definir solo limits te lleva a Guaranteed de forma implícita.",
            ],
            "cols": 3,
            "cards": [
                {"title": "Guaranteed", "body": "requests == limits en TODOS los recursos de TODOS los contenedores. Es el último en ser desalojado bajo presión."},
                {"title": "Burstable", "body": "Hay requests o limits, pero no coinciden en todo. Es el caso más habitual en producción."},
                {"title": "BestEffort", "body": "Sin requests ni limits. El PRIMERO en ser desalojado cuando el nodo se queda sin memoria."},
            ],
            "note": {"text": "Si defines solo limits, Kubernetes copia los limits a los requests y el Pod queda Guaranteed sin que lo pretendieras."},
        },
        {
            "t": "codeblocks",
            "eyebrow": "Actualización técnica",
            "heading": "Metrics Server: olvida el procedimiento antiguo",
            "accent": "warn",
            "intro": "El material original instalaba la v0.3.6 y editaba a mano la línea 42 para cambiar apiregistration v1beta1 por v1. Ese arreglo ya no aplica. Hoy se instala el manifiesto oficial tal cual.",
            "blocks": [
                {"lines": [
                    "kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/\\",
                    "download/v0.8.1/components.yaml",
                    "",
                    "# Si no llega a Ready, los LOGS te dicen por qué (certificados de kubelet):",
                    "kubectl -n kube-system logs deploy/metrics-server | tail -20",
                    "",
                    "kubectl top nodes ; kubectl top pods -A --sort-by=cpu",
                ]},
            ],
            "note": {"text": "--kubelet-insecure-tls es aceptable en laboratorio. En producción se configura la rotación de certificados de serving del kubelet."},
        },
        {
            "t": "lab",
            "level": "Nivel avanzado — solo requerimientos",
            "title": "LAB 4.3 — Recursos, QoS, escalado y métricas",
            "desc": "Dimensionar aplicaciones y provocar deliberadamente los dos fallos clásicos para reconocer su firma.",
            "steps": [
                "Instalar Metrics Server y diagnosticar por tu cuenta el argumento que falta.",
                "Tres Pods con las tres clases de QoS. Explicar la regla.",
                "Provocar un Pending por requests y un OOMKilled por limits.",
                "Explicar por qué la CPU no mata el contenedor y la memoria sí.",
                "Comparar consumo real y solicitado: ¿estás sobredimensionando?",
            ],
            "file": "CLASE-04/LABORATORIOS/LAB-03-AVANZADO.md",
            "duration": "26 min",
            "validation": "k top pods",
            "accent": "blue",
        },
        {
            "t": "lab",
            "level": "Challenge — el escenario arranca roto",
            "title": "LAB 4.4 — Challenge: el despliegue que no arranca",
            "desc": "Ninguna réplica de billing levanta. Cuatro fallos que se manifiestan por capas: hasta que no resuelves uno, no ves el siguiente.",
            "steps": [
                "Prepara el escenario: RECURSOS/SCRIPTS/setup-lab.sh",
                "Distinguir Pending, ImagePullBackOff, CreateContainerConfigError y CrashLoopBackOff.",
                "Prohibido pegar la contraseña en el manifiesto: debe venir del Secret.",
                "Objetivo: 3/3 Running y Ready, el Service responde, y el cambio queda registrado.",
            ],
            "file": "CLASE-04/LABORATORIOS/LAB-04-CHALLENGE.md",
            "duration": "20 min",
            "validation": "./validate-lab.sh",
            "accent": "danger",
        },
        {
            "t": "codeblocks",
            "eyebrow": "CKA Tip",
            "heading": "Comandos que te ahorran escribir YAML",
            "accent": "warn",
            "intro": "El nombre del contenedor no es el del Deployment. Compruébalo antes de hacer set image o perderás un intento.",
            "blocks": [
                {"lines": [
                    "k get deploy <d> -o jsonpath='{.spec.template.spec.containers[*].name}{\"\\n\"}'",
                    "k set image     deploy/<d> <cont>=<img>:<tag>",
                    "k set resources deploy/<d> --requests=cpu=100m,memory=64Mi --limits=cpu=500m,memory=256Mi",
                    "k get pod <p> -o jsonpath='{.status.qosClass}{\"\\n\"}'",
                    "k describe pod <p> | grep -A5 'Last State'      # ¿por qué murió?",
                    "k rollout restart deploy/<d>                    # recargar variables de entorno",
                ]},
            ],
        },
        {
            "t": "list",
            "eyebrow": "Checklist",
            "heading": "Comprueba que puedes hacer esto sin apuntes",
            "columns": 2,
            "style": "check",
            "items": [
                "Ejecuto un Rolling Update y sigo su progreso.",
                "Consulto el historial y el detalle de una revisión concreta.",
                "Registro la causa del cambio sin usar --record.",
                "Hago rollback a una revisión concreta.",
                "Explico maxSurge y maxUnavailable con 3 réplicas.",
                "Creo un ConfigMap de tres formas distintas.",
                "Consumo ConfigMap y Secret como variable y como volumen.",
                "Explico por qué base64 no es cifrado.",
                "Defino requests y limits y deduzco la QoS.",
                "Instalo Metrics Server y uso kubectl top.",
            ],
        },
        {
            "t": "closing",
            "eyebrow": "Cierre de la clase",
            "title": "Clase 4 completada",
            "paragraphs": [
                "Sabes actualizar, revertir, configurar y dimensionar aplicaciones.",
                "En la Clase 5 abrimos la puerta al exterior: Services, Ingress, TLS, CoreDNS y control de tráfico con NetworkPolicy. Es el 20 % del examen y donde más incidentes reales se producen.",
                "Repasa antes: la cadena Service → selector → EndpointSlice → Pod.",
            ],
        },
    ],
}
