apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gratitud.fullname" . }}
  labels:
    {{- include "gratitud.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gratitud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gratitud.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.image.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ include "gratitud.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
