apiVersion: v1
kind: ConfigMap
metadata:
  name: gratitud-config
  labels:
    {{- include "gratitud.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gratitud-db
  labels:
    {{- include "gratitud.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.db }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gratitud-tokens
  labels:
    {{- include "gratitud.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.tokens }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
